# reFuel to MOTEL unmapped records

This notebook structures the conversion of reFuel technology rows into MOTEL-compatible unmapped records.

## Goals
- Read reFuel input data from Excel.
- Load and inspect the MOTEL schema.
- Map each source row into a normalized record payload.
- Validate required fields and export records for review.

## Output target
- Write records to `dev2/motel-db/records/` as JSON or YAML files.

In [1]:
## --- load packages
from pathlib import Path
import pandas as pd
import yaml

import math
import re
from collections import defaultdict

# 1) Inputs and setup

## 1.1 Source data (reFuel Excel)

In [2]:
path_refuel = Path(r"E:\Barton\repositories\motel-platform\dev2\data\reFuel_TechDatabase_Clean_2026-06-03.xlsx")

refuel_data = pd.read_excel(path_refuel, sheet_name=None)
print(f"sheets found: {list(refuel_data.keys())}")

sheets found: ['Metadata', 'Nomenclature', 'Carrier', 'ConvTech', 'StorTech', 'EmbeddedCarbon', 'Reference']

## 1.2 Load MOTEL schema

In [3]:
path_schema = r'schema\motel_schema_rev2.yaml'

with open(path_schema, "r", encoding="utf-8") as f:
    schema_motel = yaml.safe_load(f)

print(f"Schema loaded successfully")
print(f"Type: {type(schema_motel)}")
if isinstance(schema_motel, dict):
    print(f"Top-level keys ({len(schema_motel)}): {list(schema_motel.keys())[:10]}")

Schema loaded successfully
Type: <class 'dict'>
Top-level keys (13): ['unmapped_entity', 'linked_entity', 'technology', 'process', 'source', 'contributor', 'review', 'attribute', 'carrier', 'geographic_scope']

# 2) Create secondary data from Refuel.ch data

The schema is created and then the first version of the secondary data are produced based on:
 - pre-define MOTEL schema
 - reFuel.ch tech data
 - LLM (Gemini)


For each dataset, there are two files:
1. the actual data in dataset (produce from reFuel.ch so far)
2. the map from reFuel.ch data (name or id) to motel name/id

In [4]:
# initialise the dataset and mapping data
datasets = {}

## 2.1 Technology

Technology = The "How" (The Engineering Asset)
A technology is the specific hardware, design variant, or asset configuration that actually executes a process. A single process can often be performed by several different technologies, each featuring unique efficiencies, investment costs, emission profiles, or commercial scales.

In [5]:
path_tech = r'motel-db\secondary\technologies.csv'

ds_tech = datasets['tech'] = pd.read_csv(path_tech)
ds_tech

,tech_id,technology_name,technology_description,technology_variant,main_process,main_operation_unit,ontology_iri
0,tech_00001,Ammonia CCGT Power Generation,Ammonia-fueled combined cycle gas turbine (CCG...,CCGT,Ammonia Power Generation,Gas turbine,NaN
1,tech_00002,Ammonia OCGT Power Generation,Ammonia-fueled open cycle gas turbine (OCGT) e...,OCGT,Ammonia Power Generation,Gas turbine,NaN
2,tech_00003,Methane CCGT Power Generation,Methane-fueled CCGT with carbon capture and st...,CCGT,Methane Power Generation,Gas turbine,NaN
3,tech_00004,Methane CHP Generation,Combined heat and power (CHP) generation using...,CHP plant,Methane Combined Heat and Power,Combined heat & power,NaN
4,tech_00005,Methane Fuel Cell Power Generation,Methane-fueled fuel cell electricity generatio...,SOFC,Methane Power Generation,Fuel cell,NaN
5,tech_00006,Methane Fuel Cell Generation in Buildings,Methane-fueled fuel cell electricity generatio...,SOFC,Methane Power Generation,Fuel cell,NaN
6,tech_00007,Methane OCGT Power Generation,Methane-fueled open cycle gas turbine (OCGT) e...,OCGT,Methane Power Generation,Gas turbine,NaN
7,tech_00008,Geothermal CHP Generation,Geothermal-based CHP generation (2040).,Geothermal power plant,Geothermal Combined Heat and Power,Combined heat & power,NaN
8,tech_00009,Hydrogen CCGT Power Generation,Hydrogen-fueled combined cycle gas turbine (CC...,CCGT,Hydrogen Power Generation,Gas turbine,NaN
9,tech_00010,Hydrogen Fuel Cell Power Generation,Electricity generation via fuel cells at node ...,SOFC,Hydrogen Power Generation,Fuel cell,NaN
10,tech_00011,Hydrogen Fuel Cell Generation in Buildings,Electricity generation via fuel cells in build...,SOFC,Hydrogen Power Generation,Fuel cell,NaN
11,tech_00012,Hydrogen OCGT Power Generation,Hydrogen-fueled open cycle gas turbine (OCGT) ...,OCGT,Hydrogen Power Generation,Gas turbine,NaN
12,tech_00013,Pumped Hydro Storage Pump Mode,Pumped hydroelectric energy storage (pump mode).,Pumped hydro (pump mode),Pumped Hydro Storage,Hydropower,NaN
13,tech_00014,Pumped Hydro Storage Turbine Mode,Pumped hydroelectric power generation (turbine...,Pumped hydro (turbine mode),Pumped Hydro Storage,Hydropower,NaN
14,tech_00015,Run of River Hydroelectric Generation,Run-of-river hydroelectric power plant.,Run-of-river plant,Hydroelectric Power Generation,Hydropower,NaN
15,tech_00016,Reservoir Hydroelectric Generation,Hydroelectric power generation from storage re...,Reservoir plant,Hydroelectric Power Generation,Hydropower,NaN
16,tech_00017,Municipal Solid Waste Incineration Power Gener...,Electricity generation from municipal solid wa...,Incineration plant,Waste Power Generation,Waste incineration,NaN
17,tech_00018,Alpine Solar Photovoltaic Generation,"Ground-mounted Alpine PV, from ETHZ study in 2024",Ground-mounted PV (alpine),Solar Photovoltaic Generation,Photovoltaic,NaN
18,tech_00019,Rooftop Solar Photovoltaic Generation,"Rooftop PV, small scale, in 2025",Rooftop PV,Solar Photovoltaic Generation,Photovoltaic,NaN
19,tech_00020,Uranium Nuclear Power Generation,Electricity generation from nuclear power (U23...,Pressurised water reactor,Nuclear Power Generation,Nuclear fission,NaN
20,tech_00021,Onshore Wind Turbine Generation,Generic wind turbine electricity generation (2...,Onshore wind turbine,Wind Power Generation,Wind power,NaN
21,tech_00022,Wood Biomass CHP Generation,Combined heat and power (CHP) generation using...,Biomass CHP plant,Biomass Combined Heat and Power,Combined heat & power,NaN
22,tech_00023,Methane Boiler Heating for Buildings,Methane-fueled heating system for buildings.,Gas-fired boiler,Methane Heating Systems,Boiler,NaN
23,tech_00024,Methane Boiler Heating for Industry,Methane-fueled heating system for thermal powe...,Gas-fired boiler,Methane Heating Systems,Boiler,NaN
24,tech_00025,Electric Resistance Heating for Buildings,Electric heating system for buildings.,Resistance heater,Electric Heat Generation,Electric heater,NaN
25,tech_00026,Electric Resistance Heating for Industry,Electric heating system for thermal power plants.,Resistance heater,Electric Heat Generation,Electric heater,NaN
26,tech_00027,Electric Air Conditioning Heating and Cooling,Electric cooling and heating system for buildi...,Air conditioning unit,Electric Heat Generation,Heat pump,NaN
27,tech_00028,Hydrogen Boiler Heating for Industry,Hydrogen-fueled heating system for thermal pow...,Hydrogen burner,Hydrogen Heating Systems,Boiler,NaN
28,tech_00029,Electric Heat Pump Heating for Buildings,"Generic heat pump for residential heating, fix...",Air-source heat pump,Electric Heat Generation,Heat pump,NaN
29,tech_00030,Industrial Electric Heat Pump Heating,Low-temperature heat upgrade for district heat...,Industrial heat pump,Electric Heat Generation,Heat pump,NaN
30,tech_00031,Oil Boiler Heating for Buildings,Hydrocarbon-fueled heating system for buildings.,Oil-fired boiler,Oil Heating Systems,Boiler,NaN
31,tech_00032,Oil Boiler Heating for Industry,Hydrocarbon-fueled heating system for thermal ...,Oil-fired boiler,Oil Heating Systems,Boiler,NaN
32,tech_00033,Wood Boiler Heating for Buildings,Wood-fueled heating system for buildings.,Biomass furnace,Biomass Heating Systems,Boiler,NaN
33,tech_00034,Wood Boiler Heating for Industry,Wood-fueled heating system for thermal power p...,Biomass furnace,Biomass Heating Systems,Boiler,NaN
34,tech_00035,Haber Bosch Ammonia Synthesis,Ammonia synthesis (Haber Bosch process),Haber–Bosch reactor,Ammonia Synthesis,Chemical synthesis,NaN
35,tech_00036,Wet Biomass Anaerobic Digestion,Wet biomass anaerobic digestion with gas upgra...,Anaerobic digester,Anaerobic Digestion,Anaerobic digestion,NaN
36,tech_00037,Sabatier Methanation,Methane synthesis from H2 and CO2 via the ther...,Sabatier reactor,Sabatier Methanation,Catalytic hydrogenation,NaN
37,tech_00038,HEFA Hydrotreatment for SAF,SAF Production via esterification of used cook...,HEFA reactor,HEFA Hydrotreatment,Hydrotreatment,NaN
38,tech_00039,Methanol Synthesis via CO2 Hydrogenation,Methanol synthesis from CO2 hydrogenation,Methanol synthesis reactor,Methanol Synthesis via CO2 Hydrogenation,Catalytic hydrogenation,NaN
39,tech_00040,Reverse Water Gas Shift,Reverse water gas shift reaction plant. Emergi...,RWGS reactor,Reverse Water Gas Shift,Catalytic conversion,NaN
40,tech_00041,Water Electrolysis via Alkaline Technology,"Electrolysis 2030, Alkaline technology (10 MW)...",Alkaline electrolyser,Water Electrolysis,Electrolysis,NaN
41,tech_00042,Fischer Tropsch C12 Synthesis,Hydrocarbon (C12) synthesis via Fischer-Tropsc...,FT reactor,Syngas to C12 Synthesis,Fischer–Tropsch synthesis,NaN
42,tech_00043,Fischer Tropsch C8 Synthesis,Hydrocarbon (C8) synthesis via Fischer-Tropsch...,FT reactor,Syngas to C8 Synthesis,Fischer–Tropsch synthesis,NaN
43,tech_00044,Syngas Methanation,Methane synthesis from Syngas via thermocataly...,Sabatier reactor,Syngas Methanation,Catalytic hydrogenation,NaN
44,tech_00045,Syngas to Methanol Synthesis,Methanol synthesis from Syngas via thermocatal...,Methanol synthesis reactor,Syngas to Methanol Synthesis,Catalytic hydrogenation,NaN
45,tech_00046,MSW Gasification to Syngas,Municipal solid waste gasification to syngas,Fluidised bed gasifier,MSW Gasification to Syngas,Gasification,NaN
46,tech_00047,MSW Gasification to Hydrogen,Municipal solid waste gasification to hydrogen,Fluidised bed gasifier,MSW Gasification to Hydrogen,Gasification,NaN
47,tech_00048,Wood Gasification to Hydrogen,Woody biomass gasification to hydrogen,Fluidised bed gasifier,Wood Gasification to Hydrogen,Gasification,NaN
48,tech_00049,Wood Gasification to Syngas,Woody biomass gasification to syngas,Fluidised bed gasifier,Wood Gasification to Syngas,Gasification,NaN
49,tech_00050,Methanol to Jet Conversion,Methanol-to-Jet fuel via MtO and oligomerisati...,MtO + oligomerisation reactor,Methanol-to-Jet Conversion,Hydrotreatment,NaN
50,tech_00051,High Temperature Co Electrolysis,High-temperature co-electrolysis of CO₂ and H₂...,SOEC co-electrolyser,High-Temperature Co-Electrolysis,Electrolysis,NaN
51,tech_00052,Methane Pyrolysis,Methane pyrolysis (turquoise hydrogen). Therma...,Methane pyrolysis reactor,Methane Pyrolysis,Pyrolysis,NaN
52,tech_00053,Post Combustion Amine Carbon Capture,CO2 post combustion capture via Amine washing....,Amine absorber,Post-Combustion Carbon Capture,Carbon capture,NaN
53,tech_00054,Wet Biomass Pyrolysis to Biochar,Biochar production via pyrolysis of wet biomass.,Pyrolysis reactor,Wet Biomass Pyrolysis,Pyrolysis,NaN
54,tech_00055,Direct Air Capture,Direct air capture using adsorption technology...,DAC (sorbent-based),Direct Air Capture,Carbon capture,NaN
55,tech_00056,Post Combustion PSA Carbon Capture,CO2 post combustion capture via Hot-Potassium ...,Pressure swing adsorption,Post-Combustion Carbon Capture,Carbon capture,NaN
56,tech_00057,Wood Pyrolysis to Biochar,Biochar production via pyrolysis of wood.,Pyrolysis reactor,Wood Pyrolysis,Pyrolysis,NaN

## 2.2 Process

Process = The "What" (The Functional Slot)
A process defines an abstract transformation. It maps out the strict thermodynamic or economic boundaries of the system—specifically, what goes in (feedstocks) and what comes out (products). It does not care about the exact machinery being used.

In [6]:
path_proc = r'motel-db\secondary\processes.csv'

ds_proc = datasets['proc'] = pd.read_csv(path_proc)
ds_proc

,process_id,process_name,process_description,process_type,process_category,main_sector,feedstocks,products
0,proc_00001,Ammonia Power Generation,Conversion of ammonia into network electricity...,conversion,Power Generation,power,['carrier_nh3'],['carrier_elec']
1,proc_00002,Methane Power Generation,Combustion or electrochemical conversion of me...,conversion,Power Generation,power,['carrier_ch4'],['carrier_elec']
2,proc_00003,Methane Combined Heat and Power,Simultaneous co-generation of utility power an...,conversion,Co-generation,power,['carrier_ch4'],"['carrier_elec', 'carrier_heat']"
3,proc_00004,Geothermal Combined Heat and Power,Deep geothermal extraction supplying regional ...,conversion,Co-generation,power,['carrier_geothermal_heat'],"['carrier_elec', 'carrier_heat']"
4,proc_00005,Hydrogen Power Generation,Dispatched power generation utilizing gaseous ...,conversion,Power Generation,power,['carrier_h2'],['carrier_elec']
5,proc_00006,Pumped Hydro Storage,Mechanical load-balancing via water-based pote...,storage,Energy Storage,power,['carrier_elec'],['carrier_elec']
6,proc_00007,Hydroelectric Power Generation,Kinetic and potential hydraulic energy capture...,conversion,Power Generation,power,['carrier_water_flow'],['carrier_elec']
7,proc_00008,Waste Power Generation,Thermal treatment of municipal solid waste for...,conversion,Power Generation,power,['carrier_msw'],['carrier_elec']
8,proc_00009,Solar Photovoltaic Generation,Direct solar irradiance conversion into altern...,conversion,Power Generation,power,['carrier_solar_radiation'],['carrier_elec']
9,proc_00010,Nuclear Power Generation,Controlled uranium-235 fission generating high...,conversion,Power Generation,power,['carrier_u235'],['carrier_elec']
10,proc_00011,Wind Power Generation,Kinetic atmospheric wind energy capture via on...,conversion,Power Generation,power,['carrier_wind'],['carrier_elec']
11,proc_00012,Biomass Combined Heat and Power,Thermochemical wood combustion driving co-gene...,conversion,Co-generation,power,['carrier_wood'],"['carrier_elec', 'carrier_heat']"
12,proc_00013,Methane Heating Systems,Dedicated gas combustion creating space or hig...,conversion,Heat Generation,heat,['carrier_ch4'],['carrier_heat']
13,proc_00014,Electric Heat Generation,Resistive or heat-pump driven transformation o...,conversion,Heat Generation,heat,['carrier_elec'],['carrier_heat']
14,proc_00015,Hydrogen Heating Systems,Clean combustion of hydrogen providing process...,conversion,Heat Generation,heat,['carrier_h2'],['carrier_heat']
15,proc_00016,Oil Heating Systems,Fossil liquid heating systems supplying locali...,conversion,Heat Generation,heat,['carrier_oil'],['carrier_heat']
16,proc_00017,Biomass Heating Systems,Woody fuel combustion for building or factory ...,conversion,Heat Generation,heat,['carrier_wood'],['carrier_heat']
17,proc_00018,Ammonia Synthesis,Fixation of nitrogen and hydrogen into anhydro...,conversion,Chemical Synthesis,industry,"['carrier_h2', 'carrier_n2']",['carrier_nh3']
18,proc_00019,Anaerobic Digestion,Upgrading wet biomass waste streams into clean...,conversion,Anaerobic Digestion,industry,['carrier_biowet'],['carrier_ch4']
19,proc_00020,Sabatier Methanation,Methane synthesis from hydrogen and CO2 via th...,conversion,Chemical Synthesis,industry,"['carrier_h2', 'carrier_co2']",['carrier_ch4']
20,proc_00021,HEFA Hydrotreatment,Sustainable aviation fuel production via ester...,conversion,Chemical Synthesis,transport,['carrier_cookingoil'],['carrier_saf']
21,proc_00022,Methanol Synthesis via CO2 Hydrogenation,Catalytic hydrogenation of carbon dioxide stre...,conversion,Chemical Synthesis,industry,"['carrier_h2', 'carrier_co2']",['carrier_meoh']
22,proc_00023,Reverse Water Gas Shift,Endothermic production of carbon monoxide from...,conversion,Chemical Synthesis,industry,"['carrier_h2', 'carrier_co2']",['carrier_co']
23,proc_00024,Water Electrolysis,Electrochemical splitting of water into hydrog...,conversion,Hydrogen Production,industry,['carrier_elec'],['carrier_h2']
24,proc_00025,Syngas to C12 Synthesis,Catalytic polymerization of syngas components ...,conversion,Chemical Synthesis,industry,['carrier_syngas'],['carrier_c12']
25,proc_00026,Syngas to C8 Synthesis,Catalytic polymerization of syngas components ...,conversion,Chemical Synthesis,industry,['carrier_syngas'],['carrier_c8']
26,proc_00027,Syngas Methanation,Thermocatalytic conversion of synthesis gas st...,conversion,Chemical Synthesis,industry,['carrier_syngas'],['carrier_ch4']
27,proc_00028,Syngas to Methanol Synthesis,Thermocatalytic processing of syngas into liqu...,conversion,Chemical Synthesis,industry,['carrier_syngas'],['carrier_meoh']
28,proc_00029,MSW Gasification to Syngas,Partial oxidation of municipal solid waste opt...,conversion,Gasification,industry,['carrier_msw'],['carrier_syngas']
29,proc_00030,MSW Gasification to Hydrogen,Partial oxidation of municipal solid waste opt...,conversion,Gasification,industry,['carrier_msw'],['carrier_h2']
30,proc_00031,Wood Gasification to Hydrogen,Thermochemical cracking of woody biomass optim...,conversion,Gasification,industry,['carrier_wood'],['carrier_h2']
31,proc_00032,Wood Gasification to Syngas,Thermochemical conversion of woody biomass opt...,conversion,Gasification,industry,['carrier_wood'],['carrier_syngas']
32,proc_00033,Methanol-to-Jet Conversion,Dehydration and oligomerisation pathways conve...,conversion,Chemical Synthesis,transport,['carrier_meoh'],['carrier_saf']
33,proc_00034,High-Temperature Co-Electrolysis,Simultaneous high-temperature electrolysis of ...,conversion,Electrolysis,industry,"['carrier_elec', 'carrier_co2']",['carrier_syngas']
34,proc_00035,Methane Pyrolysis,Thermal splitting of methane gas into clean hy...,conversion,Pyrolysis,industry,['carrier_ch4'],"['carrier_h2', 'carrier_carbon_solid']"
35,proc_00036,Post-Combustion Carbon Capture,Isolating clean CO2 molecules from power or fa...,conversion,Carbon Capture,industry,['carrier_flue_gas'],['carrier_co2']
36,proc_00037,Wet Biomass Pyrolysis,Thermochemical treatment of wet biomass matric...,other,Carbon Sequestration,industry,['carrier_biowet'],['carrier_biochar']
37,proc_00038,Direct Air Capture,Adsorption frameworks removing carbon dioxide ...,conversion,Carbon Capture,industry,['carrier_air'],['carrier_co2']
38,proc_00039,Wood Pyrolysis,Thermochemical degradation of dry wood element...,other,Carbon Sequestration,industry,['carrier_wood'],['carrier_biochar']

## 2.3 Source

In [7]:
path_src = r'motel-db\secondary\sources.csv'

ds_src = datasets['src'] = pd.read_csv(path_src)
ds_src

,source_id,source_name,description,source_type,link,note,access_date
0,src_00001,Allgöwer PATHFNDER Study,Paper by ETH from PATHFNDER,paper,https://doi.org/10.1021/acs.iecr.4c01287,NaN,NaN
1,src_00002,Empa Rheintal Study,"Rheintal paper of Empa, submitted 2025",paper,https://dx.doi.org/10.2139/ssrn.5291581,NaN,NaN
2,src_00003,Journal of Cleaner Production Biochar Study,Financial feasibility of biochar production: A...,paper,https://doi.org/10.1016/j.jclepro.2025.147167,NaN,NaN
3,src_00004,Future Energy Hydropower Framework,Future Energy (Third Edition),paper,https://doi.org/10.1016/B978-0-08-102886-5.000...,NaN,NaN
4,src_00005,CCGT and CCS Integration Modelling Study,Off-design point modelling of a 420 MW CCGT po...,paper,https://doi.org/10.1016/j.apenergy.2016.06.087,This wasn't used anywhere in the db?,NaN
5,src_00006,Electricity Market Combined Cycle Modelling Study,Modelling combined-cycle power plants in a det...,paper,https://doi.org/10.1016/j.energy.2024.131246,NaN,NaN
6,src_00007,Municipal Solid Waste Gasification Review,Municipal Solid Waste Gasification: Technologi...,paper,https://doi.org/10.3390/su17156704,NaN,NaN
7,src_00008,Renewable Cost Projections Review,"review the cost projection of PV, wind, battery",paper,https://doi.org/10.1016/j.apenergy.2025.125856,NaN,NaN
8,src_00009,RWGS Coupled Catalytic Reactions Study,Technology Readiness and Emerging Prospects of...,paper,https://doi.org/10.1002/cssc.202400865,NaN,NaN
9,src_00010,ETHZ Alpine PV Viability Study,ETHZ paper on Alpine PV cost and financial via...,paper,https://doi.org/10.1016/j.apenergy.2024.124019,NaN,NaN
10,src_00011,Biogas-to-Biomethane Upgrading Assessment,Biogas-to-biomethane upgrading: A comparative ...,paper,https://doi.org/10.1016/j.rser.2020.110588,NaN,NaN
11,src_00012,Aviation E-Fuel Production Framework,Forging a sustainable sky: Unveiling the pilla...,paper,https://doi.org/10.1016/j.isci.2024.109154,NaN,NaN
12,src_00013,Mutschler Catalytic Kinetics Study,NaN,paper,https://doi.org/10.1016/j.jcat.2018.08.002,NaN,NaN
13,src_00014,Müller Power-to-X Costs Review,The costs of future energy technologies: A com...,paper,https://doi.org/10.1016/j.jcou.2025.103019,NaN,NaN
14,src_00015,Biomass Gasification Technologies Assessment,Cutting-edge biomass gasification technologies...,paper,https://doi.org/10.1016/j.enconman.2024.119213,NaN,NaN
15,src_00016,Power-to-Ammonia Renewable Systems Report,Power-to-ammonia in future North European 100 ...,paper,https://doi.org/10.1016/j.ijhydene.2018.06.121,NaN,NaN
16,src_00017,VSE Energiezukunft 2050 Study,"VSE Energiezukunft 2050, Studie 2022",report,https://www.strom.ch/de/energiezukunft-2050/do...,NaN,2023-09-06
17,src_00018,VSE Energiezukunft 2050 Update,"VSE Energiezukunft 2050, Update 2025",report,https://www.strom.ch/de/energiezukunft-2050/do...,NaN,2025-05-26
18,src_00019,Alpvolt Swiss Battery Market Analysis,article about market price of home batteries i...,web,https://alpvolt.com/en/news/solar-batteries-in...,NaN,NaN
19,src_00020,NREL ATB Battery Cost Framework,FOM costs are estimated at 2.5% of the capital...,web,https://atb.nrel.gov/electricity/2024/utility-...,NaN,NaN
20,src_00021,BFE Energieperspektiven 2050 Plus NET and CCS ...,"BFE Energieperspektiven 2050+, Excursus on Neg...",report,https://www.bfe.admin.ch/bfe/en/home/politik/e...,NaN,NaN
21,src_00022,ASSET Decarbonisation Technology Pathways,ASSET: Technology pathways in decarbonisation ...,report,https://build-up.ec.europa.eu/sites/default/fi...,NaN,NaN
22,src_00023,OST Gas Compression Energy Evaluation,Energieaufwand für Gaskomprimierung (November ...,report,https://www.ost.ch/fileadmin/dateiliste/3_fors...,NaN,NaN
23,src_00024,IEA Bioenergy Hydrogen Production Analysis,Biomass gasification for hydrogen production,report,https://www.ieabioenergy.com/wp-content/upload...,NaN,NaN
24,src_00025,Empa Baseline Expert Assumption,Expert Assumption,assumption,NaN,NaN,NaN
25,src_00026,Empa Project Expert Assumption,Expert assumptions and calculations by Empa,assumption,NaN,NaN,NaN
26,src_00027,ReFuel Work Package 3 Expert Assumption,Expert Assumption,assumption,NaN,NaN,NaN
27,src_00028,AECOM Carbon Capture Technoeconomic Analysis,AECOM 2022: Next Generation Carbon Capture Tec...,report,NaN,NaN,NaN
28,src_00029,Post-Combustion Carbon Capture Comparative Ass...,Postcombustion CO2 Capture: A Comparative Tech...,paper,https://doi.org/10.1021/acsengineeringau.1c00002,NaN,NaN
29,src_00030,Empa Photovoltaic Operational Cost Assumption,"currently FOM is 15-25 CHF/kW.year, may reduce...",assumption,NaN,NaN,NaN
30,src_00031,Empa Battery Capital Cost Assumption,assumption based on various info,assumption,NaN,NaN,NaN
31,src_00032,Empa Biogas Plant Efficiency Operational Assum...,Overall Efficiency estimatin of biogas plants:...,assumption,NaN,NaN,NaN
32,src_00033,Photovoltaic Yearly Cost Reduction Projection,4/3/2% cost reduction per year in 2030/2040/20...,assumption,NaN,NaN,NaN
33,src_00034,Reaction Input-Output Stoichiometric Conversion,Calculating Input Output Ratios of Reactions,calculation,NaN,NaN,NaN
34,src_00035,Life Cycle Assessment Parameters Framework,LCA Parameters,database,NaN,NaN,NaN
35,src_00036,Danish Energy Agency Technology Dataset 2025,Report from Danish Energy Agency,report,https://ens.dk/technologydata,NaN,2025-09-19
36,src_00037,Danish Energy Agency Technology Dataset 2026,Report from Danish Energy Agency,report,NaN,NaN,NaN
37,src_00038,Swiss Natural Gas Storage Capacity Report,Speicherkapazität von Erdgas in der Schweiz (2...,report,NaN,cannot find the link of the report,NaN
38,src_00039,IEA Global Hydrogen Review,he Global Hydrogen Review 2024 systematically ...,report,https://iea.blob.core.windows.net/assets/89c1e...,NaN,NaN
39,src_00040,Joint Research Centre Technical Report,NaN,report,https://doi.org/10.2760/527879,NaN,NaN
40,src_00041,Process Input-Output Share Allocation Reference,Temporary reference ID for input and output sh...,assumption,NaN,NaN,NaN

## 2.4 Attribute

note: exclude attirbutes for balancing, deal with it for balancing later

In [8]:
path_attr = r'motel-db\controlled_vocabulary\attributes.csv'

ds_attr = datasets['attr'] = pd.read_csv(path_attr)
ds_attr

,attribute_id,attribute_name,attribute_description,unit,data_format,note
0,ATTR_TECHNICAL_EFFICIENCY,technical_efficiency,Overall energy conversion efficiency: main out...,-,float,Based on kW output capacity / LHV (chemical) e...
1,ATTR_TECHNOLOGY_READINESS_LEVEL,technology_readiness_level,Technology Readiness Level on the standard 1–9...,-,int,See Nomenclature A-3.
2,ATTR_TECH_MATURITY,tech_maturity,Aggregated maturity classification derived fro...,-,text,See Nomenclature A-2.
3,ATTR_REFERENCE_UNIT_SIZE,reference_unit_size,Nameplate capacity on which all specific cost ...,CAP,float,Capacity basis for scaling.
4,ATTR_THEORETICAL_EFFICIENCY,theoretical_efficiency,Ratio of the main output's energy content (LHV...,-,float,May be blank if not applicable.
5,ATTR_OPERATING_TEMPERATURE,operating_temperature,Typical operating temperature of the process.,°C,float,Relevant for thermal integration.
6,ATTR_POWER_CAPACITY_MIN,power_capacity_min,Smallest assumed unit capacity for the technol...,CAP,float,0 if no minimum constraint.
7,ATTR_LIFETIME_ECONOMIC,lifetime_economic,Economic lifetime of the asset.,yr,int,Expected operational lifetime.
8,ATTR_CAPEX_ONE_TIME,capex_one_time,Fixed capital expenditure (independent of size).,CUR,float,For project lump sum.
9,ATTR_OPEX_FIX_PCT_OF_CAPEX,opex_fix_pct_of_capex,Fixed annual operational expenditure expressed...,%,float,-
10,ATTR_OPEX_PER_CAPACITY_YR,opex_per_capacity_yr,Fixed annual operational expenditure per unit ...,CUR / CAP.yr,float,-
11,ATTR_OPEX_PER_ENERGY,opex_per_energy,Variable operational expenditure per unit of e...,CUR / CAP.hr,float,-
12,ATTR_DISCOUNT_RATE_PCT,discount_rate_pct,Technology-specific weighted average cost of c...,%,float,> 0
13,ATTR_UNCERTAINTY_RATING,uncertainty_rating,Flag indicating whether parameter values have ...,-,text,See Nomenclature.
14,ATTR_STORAGE_CARRIER,storage_carrier,The physical medium of storage (e.g.; 'Li-Ion'...,-,text,Carrier abbreviation. Reference Carrier tab.
15,ATTR_STORAGE_CAPACITY_MIN,storage_capacity_min,Smallest assumed storage capacity.,kWh,float,> 0
16,ATTR_CHARGING_CAPACITY_FACTOR,charging_capacity_factor,Maximum charging power as fraction of rated st...,1 / h,float,0 – 1
17,ATTR_DISCHARGING_CAPACITY_FACTOR,discharging_capacity_factor,Maximum discharging power as fraction of rated...,1 / h,float,0 – 1
18,ATTR_CHARGING_EFFICIENCY,charging_efficiency,Energy efficiency during charging.,-,float,0 – 1
19,ATTR_DISCHARGING_EFFICIENCY,discharging_efficiency,Energy efficiency during discharging.,-,float,0 – 1
20,ATTR_SOC_MIN,soc_min,Minimum state of charge as fraction of total c...,-,float,0 – 1
21,ATTR_SOC_MAX,soc_max,Maximum state of charge as fraction of total c...,-,float,0 – 1
22,ATTR_SELF_DISCHARGE_RATE,self_discharge_rate,Fractional energy loss per hour during standby...,1 / h,float,> 0
23,ATTR_CAPEX_PER_STOR_CAPACITY,capex_per_stor_capacity,Specific capital expenditure per unit of insta...,CUR / kWh,float,Primary scaling parameter (StorTech).
24,ATTR_OPEX_ONE_TIME,opex_one_time,Fixed one-time operational expenditure indepen...,CUR,float,-

## 2.X Mappings from reFuel.ch to MOTEL

In [9]:
mappings = {}

In [10]:
path_map_tech = 'motel-db/mapping/refuel/map_tech.csv'

map_tech = mappings['tech'] = pd.read_csv(path_map_tech)
map_tech

,previous_technology_name,new_technology_name
0,NH3_CCGT_El,Ammonia CCGT Power Generation
1,NH3_OCGT_El,Ammonia OCGT Power Generation
2,CH4_CCGT_El,Methane CCGT Power Generation
3,CH4_CHP_ElTh,Methane CHP Generation
4,CH4_FuelCell_El,Methane Fuel Cell Power Generation
5,CH4_FuelCell_ElBdg,Methane Fuel Cell Generation in Buildings
6,CH4_OCGT_El,Methane OCGT Power Generation
7,Geothermal_CHP_ElTh,Geothermal CHP Generation
8,H2_CCGT_El,Hydrogen CCGT Power Generation
9,H2_FuelCell_El,Hydrogen Fuel Cell Power Generation
10,H2_FuelCell_ElBdg,Hydrogen Fuel Cell Generation in Buildings
11,H2_OCGT_El,Hydrogen OCGT Power Generation
12,El_PumpedHydro_Pump,Pumped Hydro Storage Pump Mode
13,Hydro_PumpedTurbine_El,Pumped Hydro Storage Turbine Mode
14,Hydro_RunOfRiver_El,Run of River Hydroelectric Generation
15,Hydro_Reservoir_El,Reservoir Hydroelectric Generation
16,MSW_Incineration_El,Municipal Solid Waste Incineration Power Gener...
17,Solar_PVAlpine_El,Alpine Solar Photovoltaic Generation
18,Solar_PVRooftop_El,Rooftop Solar Photovoltaic Generation
19,U235_Nuclear_El,Uranium Nuclear Power Generation
20,Wind_Turbine_El,Onshore Wind Turbine Generation
21,Wood_CHP_ElTh,Wood Biomass CHP Generation
22,CH4_Boiler_ThBdg,Methane Boiler Heating for Buildings
23,CH4_Boiler_ThInd,Methane Boiler Heating for Industry
24,El_Heater_ThBdg,Electric Resistance Heating for Buildings
25,El_Heater_ThInd,Electric Resistance Heating for Industry
26,El_AirCon_ThSc,Electric Air Conditioning Heating and Cooling
27,H2_Boiler_ThInd,Hydrogen Boiler Heating for Industry
28,El_HeatPump_ThBdg,Electric Heat Pump Heating for Buildings
29,El_HeatPump_ThInd,Industrial Electric Heat Pump Heating
30,Oil_Boiler_ThBdg,Oil Boiler Heating for Buildings
31,Oil_Boiler_ThInd,Oil Boiler Heating for Industry
32,Wood_Boiler_ThBdg,Wood Boiler Heating for Buildings
33,Wood_Boiler_ThInd,Wood Boiler Heating for Industry
34,H2_HaberBosch_NH3,Haber Bosch Ammonia Synthesis
35,BioWet_Digestion_CH4,Wet Biomass Anaerobic Digestion
36,H2_Sabatier_CH4,Sabatier Methanation
37,CookingOil_HEFA_C12,HEFA Hydrotreatment for SAF
38,H2_CO2Hydro_MeOH,Methanol Synthesis via CO2 Hydrogenation
39,H2_RWGS_CO,Reverse Water Gas Shift
40,El_Electrolysis_H2,Water Electrolysis via Alkaline Technology
41,Syngas_FT_C12,Fischer Tropsch C12 Synthesis
42,Syngas_FT_C8,Fischer Tropsch C8 Synthesis
43,Syngas_COHydro_CH4,Syngas Methanation
44,Syngas_COHydro_MeOH,Syngas to Methanol Synthesis
45,MSW_Gasification_Syngas,MSW Gasification to Syngas
46,MSW_Gasification_H2,MSW Gasification to Hydrogen
47,Wood_Gasification_H2,Wood Gasification to Hydrogen
48,Wood_Gasification_Syngas,Wood Gasification to Syngas
49,MeOH_MtJ_C12,Methanol to Jet Conversion
50,El_CoElectrolysis_Syngas,High Temperature Co Electrolysis
51,CH4_Pyrolysis_H2,Methane Pyrolysis
52,CO2Flue_AmineScrub_CO2,Post Combustion Amine Carbon Capture
53,BioWet_Pyrolysis_Biochar,Wet Biomass Pyrolysis to Biochar
54,Air_DAC_CO2,Direct Air Capture
55,CO2Flue_PSA_CO2,Post Combustion PSA Carbon Capture
56,Wood_Pyrolysis_Biochar,Wood Pyrolysis to Biochar

In [11]:
path_map_src = 'motel-db/mapping/refuel/map_src.csv'

map_src = mappings['src'] = pd.read_csv(path_map_src)

# dict consumed by parse_source_text: reFuel source_id -> MOTEL source_name
map_src_id = dict(zip(map_src['previous_source_id'], map_src['new_source_name']))
map_src

,previous_source_id,new_source_name
0,Allgoewer_2024,Allgöwer PATHFNDER Study
1,rheintal_2025,Empa Rheintal Study
2,biochar_jcp_2025,Journal of Cleaner Production Biochar Study
3,book_hydropower_2020,Future Energy Hydropower Framework
4,paper_CCGT+CCS_2016,CCGT and CCS Integration Modelling Study
5,paper_CCGT_2024,Electricity Market Combined Cycle Modelling Study
6,paper_Msw to syngas,Municipal Solid Waste Gasification Review
7,paper_PVcostProjection_2025,Renewable Cost Projections Review
8,paper_RWGS,RWGS Coupled Catalytic Reactions Study
9,paper_alpinePV_2024,ETHZ Alpine PV Viability Study
10,paper_biogas,Biogas-to-Biomethane Upgrading Assessment
11,paper_e-fuel production,Aviation E-Fuel Production Framework
12,paper_mutschler_2018,Mutschler Catalytic Kinetics Study
13,paper_müller_PowerX_2025,Müller Power-to-X Costs Review
14,paper_biomass to syngas,Biomass Gasification Technologies Assessment
15,report_power_to_ammonia_2018,Power-to-Ammonia Renewable Systems Report
16,report_VSE_2022,VSE Energiezukunft 2050 Study
17,report_VSE_2025,VSE Energiezukunft 2050 Update
18,web_BatteryCH_2023,Alpvolt Swiss Battery Market Analysis
19,web_Battery_OM_2025,NREL ATB Battery Cost Framework
20,report_BFE_EP2050plus_CCS_2020,BFE Energieperspektiven 2050 Plus NET and CCS ...
21,report_ASSET_2018,ASSET Decarbonisation Technology Pathways
22,report_gas_compression_2014,OST Gas Compression Energy Evaluation
23,report_wood to hydrogen,IEA Bioenergy Hydrogen Production Analysis
24,assumption_Empa_2022,Empa Baseline Expert Assumption
25,assumption_Empa_2025,Empa Project Expert Assumption
26,assumption_reFuelWP3_2025,ReFuel Work Package 3 Expert Assumption
27,AECOM_2022,AECOM Carbon Capture Technoeconomic Analysis
28,paper_Postcom_2021,Post-Combustion Carbon Capture Comparative Ass...
29,assumption_Empa_PV_OM,Empa Photovoltaic Operational Cost Assumption
30,assumption_Empa_battery_capex_2025,Empa Battery Capital Cost Assumption
31,assumption_Empa_danish_energy_OE,Empa Biogas Plant Efficiency Operational Assum...
32,assumption_PVcostProjection,Photovoltaic Yearly Cost Reduction Projection
33,conversion_parametrization,Reaction Input-Output Stoichiometric Conversion
34,parameters_lca,Life Cycle Assessment Parameters Framework
35,report_danish_energy_2025,Danish Energy Agency Technology Dataset 2025
36,report_danish_energy_2026,Danish Energy Agency Technology Dataset 2026
37,report_gas_storage_2017,Swiss Natural Gas Storage Capacity Report
38,report_global_hydrogen_review_2024,IEA Global Hydrogen Review
39,report_jrc_2021,Joint Research Centre Technical Report
40,source_share,Process Input-Output Share Allocation Reference

In [12]:
path_map_attr = 'motel-db/mapping/refuel/map_attr.csv'

df_attr_mapping = pd.read_csv(path_map_attr)
df_attr_mapping

,Raw Attribute,Cleaned attribute_name,Assigned Target attribute_id
0,technical_efficiency,technical_efficiency,ATTR_TECHNICAL_EFFICIENCY
1,trl,technology_readiness_level,ATTR_TECHNOLOGY_READINESS_LEVEL
2,tech_maturity,tech_maturity,ATTR_TECH_MATURITY
3,reference_unit_size,reference_unit_size,ATTR_REFERENCE_UNIT_SIZE
4,theoretical_efficiency,theoretical_efficiency,ATTR_THEORETICAL_EFFICIENCY
5,operating_temperature_c,operating_temperature,ATTR_OPERATING_TEMPERATURE
6,min_installation_size,power_capacity_min,ATTR_POWER_CAPACITY_MIN
7,lifetime_yr,lifetime_economic,ATTR_LIFETIME_ECONOMIC
8,capex_one_time,capex_one_time,ATTR_CAPEX_ONE_TIME
9,opex_fix_pct_of_capex,opex_fix_pct_of_capex,ATTR_OPEX_FIX_PCT_OF_CAPEX
10,opex_per_capacity_yr,opex_per_capacity_yr,ATTR_OPEX_PER_CAPACITY_YR
11,opex_per_energy,opex_per_energy,ATTR_OPEX_PER_ENERGY
12,discount_rate_pct,discount_rate_pct,ATTR_DISCOUNT_RATE_PCT
13,uncertainty_rating,uncertainty_rating,ATTR_UNCERTAINTY_RATING
14,storage_carrier,storage_carrier,ATTR_STORAGE_CARRIER
15,min_installation,storage_capacity_min,ATTR_STORAGE_CAPACITY_MIN
16,charging_capacity_factor,charging_capacity_factor,ATTR_CHARGING_CAPACITY_FACTOR
17,discharging_capacity_factor,discharging_capacity_factor,ATTR_DISCHARGING_CAPACITY_FACTOR
18,charging_efficiency,charging_efficiency,ATTR_CHARGING_EFFICIENCY
19,discharging_efficiency,discharging_efficiency,ATTR_DISCHARGING_EFFICIENCY
20,min_soc,soc_min,ATTR_SOC_MIN
21,max_soc,soc_max,ATTR_SOC_MAX
22,standby_loss_per_hour,self_discharge_rate,ATTR_SELF_DISCHARGE_RATE
23,capex_per_stor_capacity,capex_per_stor_capacity,ATTR_CAPEX_PER_STOR_CAPACITY
24,opex_one_time,opex_one_time,ATTR_OPEX_ONE_TIME

## 2.X Data validation

Check if the data in the seconary dataset are correct
1. validate the data format based on schema
2. check the id and name are unique
3. check the link between tech and process are matched

In [13]:
import os
from pathlib import Path
import pandas as pd
import yaml


def validate_csv(df, schema):
    # TODO: how/what is validated here?

    # Skip validation for 'category' and 'description' columns
    schema = {k: v for k, v in schema.items() if k not in ['category', 'description']}
    df_columns = [col for col in df.columns if col not in ['category', 'description']]
    
    # Validate against schema (for simplicity, checking if all keys in schema exist in DataFrame columns)
    matched_columns = set(schema.keys()) & set(df_columns)
    if matched_columns:
        print("Matched Columns:", list(matched_columns))

    missing_keys = set(schema.keys()) - set(df_columns)
    if missing_keys:
        print("Missing Columns:", list(missing_keys))    

    extra_keys = set(df_columns) - set(schema.keys())
    if extra_keys:
        print(f"Extra keys: {extra_keys}\n")

    if missing_keys or extra_keys:
        print("The DataFrame does not match the schema\n")
        return False
    
    print(f"DataFrame follows the schema\n")
    
    return True


# Get the last three CSV files
di_datasets = {
    'technology': ds_tech,
    'process': ds_proc,
    'source': ds_src
    }

# Validate each of the last three CSV files against the schema
for ds_nam, df in di_datasets.items():
    validate_csv(df, schema_motel[ds_nam])

Matched Columns: ['technology_name', 'tech_id', 'main_process', 'technology_description', 'ontology_iri', 'technology_variant', 'main_operation_unit']
DataFrame follows the schema

Matched Columns: ['process_type', 'process_name', 'feedstocks', 'main_sector', 'process_id', 'process_category', 'process_description', 'products']
DataFrame follows the schema

Matched Columns: ['source_id', 'source_type', 'access_date', 'link', 'source_name', 'note']
Missing Columns: ['assessment_method', 'source_description', 'confidence_level', 'assessment_date']
The DataFrame does not match the schema

# 3) Create unmapped recrods from reFuel.ch data

## 3.1 Convert/map the reFuel.ch data to unmapped records

In [14]:
## load the ConvTech
sheet_name = 'ConvTech'
df_convtech = refuel_data[sheet_name].copy()

## correct column names
df_convtech.columns = df_convtech.loc[1]
df_convtech = df_convtech.loc[2:].reset_index(drop=True)

# deal with tech_category not in a column: add tech_category
df_convtech.insert(0, 'tech_category', pd.NA)
indx_filter = df_convtech[df_convtech['tech_type'].isna()].index

df_convtech.loc[indx_filter, 'tech_category'] = df_convtech.loc[indx_filter, 'tech_id']

df_convtech['tech_category'] = df_convtech['tech_category'].ffill(inplace=True)
df_convtech = df_convtech[df_convtech['tech_type'].notna()].reset_index(drop=True)

df_convtech

1,tech_category,tech_id,tech_year,technology_class,description,unit_operation,tech_type,reference_unit_size,cost_base,currency,...,opex_per_energy,discount_rate_pct,value_range_check,uncertainty_rating,mass_inflows,mass_outflows,energy_balance_error_pct,mass_balance_error_pct,balance_pass_flag,list_of_source_id
0,Electricity generation,NH3_CCGT_El,2050,Gas turbine,NaN,CCGT,Conversion,NaN,ECA,EUR,...,0.002,NaN,true,NaN,"1216, 1714",1000,0.6906,0.0122,true,"""capex_per_capacity"", ""opex_per_capacity_yr"", ..."
1,Electricity generation,NH3_OCGT_El,2050,Gas turbine,NaN,OCGT,Conversion,NaN,ECA,EUR,...,0.002,NaN,true,NaN,"1216, 1714",1000,0.6906,0.0122,true,"""capex_per_capacity"", ""opex_per_capacity_yr"", ..."
2,Electricity generation,CH4_CCGT_El,2050,Gas turbine,Methane-fueled CCGT with carbon capture and st...,CCGT,Conversion,NaN,ECA,EUR,...,0.002,NaN,true,Low,na,na,0.0600,0.0000,true,"""technical_efficiency"": paper_CCGT_2024; ""cap..."
3,Electricity generation,CH4_CHP_ElTh,2050,Combined heat & power,Combined heat and power (CHP) generation using...,CHP plant,Conversion,NaN,ECA,EUR,...,0.004,NaN,true,Low,na,na,0.0600,0.0000,true,"""capex_per_capacity"", ""opex_per_capacity_yr"",..."
4,Electricity generation,CH4_FuelCell_El,2030,Fuel cell,Methane-fueled fuel cell electricity generatio...,SOFC,Conversion,NaN,ECA,EUR,...,0,NaN,true,Medium,na,na,na,na,na,"""capex_per_capacity"", ""opex_per_capacity_yr"", ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Carbon capture & sequestration,Air_DAC_CO2,2050,Carbon capture,Direct air capture using adsorption technology...,DAC (sorbent-based),Conversion,NaN,ECA,EUR,...,0,NaN,true,High,na,na,na,na,na,"""capex_per_capacity"", ""opex_per_capacity_yr"", ..."
95,Carbon capture & sequestration,CO2Flue_PSA_CO2,2030,Carbon capture,CO2 post combustion capture via Hot-Potassium ...,Pressure swing adsorption,Conversion,20,ECA,EUR,...,0.0022 EUR/kg,NaN,true,High,na,na,na,na,na,"""capex_per_capacity"", ""opex_per_capacity_yr"", ..."
96,Carbon capture & sequestration,CO2Flue_PSA_CO2,2040,Carbon capture,CO2 post combustion capture via Hot-Potassium ...,Pressure swing adsorption,Conversion,20,ECA,EUR,...,0.0022 EUR/kg,NaN,true,High,na,na,na,na,na,"""capex_per_capacity"", ""opex_per_capacity_yr"", ..."
97,Carbon capture & sequestration,CO2Flue_PSA_CO2,2050,Carbon capture,CO2 post combustion capture via Hot-Potassium ...,Pressure swing adsorption,Conversion,20,ECA,EUR,...,0.0022 EUR/kg,NaN,true,High,na,na,na,na,na,"""capex_per_capacity"", ""opex_per_capacity_yr"", ..."
98,Carbon capture & sequestration,Wood_Pyrolysis_Biochar,2025,Pyrolysis,Biochar production via pyrolysis of wood.,Pyrolysis reactor,Conversion,0.05,ECA,EUR,...,0,NaN,true,High,na,na,na,na,na,"""capex_per_capacity"", ""opex_per_capacity_yr"",..."

In [15]:
## supportive functions

def is_nan(value):
    return value is None or (
        isinstance(value, float) and math.isnan(value)
    )


def clean(value):
    return None if is_nan(value) else value


def parse_number_with_unit(text):
    """
    Converts:
        '2800 CHF/kg/h'
    into:
        (2800.0, 'CHF/kg/h')
    """
    if not isinstance(text, str):
        return text, None

    match = re.match(r"^\s*([0-9.]+)\s*(.*)$", text)
    if match:
        return float(match.group(1)), match.group(2).strip()

    return text, None


def split_csv(value):
    if is_nan(value):
        return []
    return [
        x.strip()
        for x in str(value).split(",")
        if x.strip() and x.strip().lower() not in {"na", "nan"}
    ]


def split_csv_float(value):
    out = []
    for token in split_csv(value):
        try:
            out.append(float(token))
        except ValueError:
            out.append(None)
    return out


def split_number_unit(value):
    """Split strings like '20000 kg/h' into (20000.0, 'kg/h').

    Returns (original_value, None) when no numeric+unit pattern is found.
    """
    if not isinstance(value, str):
        return value, None

    text = value.strip()
    if not text:
        return value, None

    match = re.match(r"^([-+]?\d[\d,]*(?:\.\d+)?)\s+(.+)$", text)
    if not match:
        return value, None

    number_text, unit_text = match.groups()
    unit_text = unit_text.strip()
    if not unit_text:
        return value, None

    try:
        numeric_value = float(number_text.replace(",", ""))
    except ValueError:
        return value, None

    return numeric_value, unit_text


def is_empty_like_base(value):
    """Return True for empty / NA-like values used for final record pruning."""
    if is_nan(value):
        return True

    if isinstance(value, str):
        token = value.strip().lower()
        return token in {"", "na", "nan", "none", "null", "n/a"}

    if isinstance(value, (list, tuple, set)):
        return len(value) == 0 or all(is_empty_like_base(v) for v in value)

    if isinstance(value, dict):
        return len(value) == 0 or all(is_empty_like_base(v) for v in value.values())

    return False


def is_empty_like(value):
    """Return True for empty / NA-like values.

    Empty-like values include None, NaN, empty strings, and textual NA markers.
    Containers are considered empty when all contained values are empty-like.
    """
    if is_nan(value):
        return True

    if isinstance(value, str):
        token = value.strip().lower()
        return token in {"", "na", "nan", "none", "null", "n/a"}

    if isinstance(value, (list, tuple, set)):
        return len(value) == 0 or all(is_empty_like(v) for v in value)

    if isinstance(value, dict):
        return len(value) == 0 or all(is_empty_like(v) for v in value.values())

    return False

In [16]:
# LAYER 1 (BASE): core row -> record mapping.
# This cell defines the base implementation of map_technology and helpers.
# Balancing is built directly in final target schema here.
## --- function to convert reFuel.ch data into 'unmapped record'


def add_value(values, name, description, value, unit=None, scenario=None, time_index=None):
    """Append one attribute if and only if value is non-empty.

    Also supports overriding default unit when value embeds unit text,
    e.g., value='20000 kg/h' with default unit='kW or kg/h'.
    """
    if is_empty_like(value):
        return

    parsed_value, parsed_unit = split_number_unit(value)
    if parsed_unit:
        value = parsed_value
        unit = parsed_unit

    record = {
        "attribute_name": name,
        "attribute_description": description,
        "unit": unit,
        "value": value,
    }

    if scenario:
        record["scenario"] = scenario

    if time_index:
        record["time_index"] = time_index

    values.append(record)


def build_balancing_entries(carriers, shares, units):
    size = max(len(carriers), len(shares), len(units))
    entries = []

    for i in range(size):
        carrier = carriers[i] if i < len(carriers) else None
        share = shares[i] if i < len(shares) else None
        unit = units[i] if i < len(units) else None

        if carrier is None and share is None and unit is None:
            continue

        entries.append({
            "carrier": carrier,
            "share": share,
            "unit": unit,
        })

    return entries


def to_balance_list(items):
    """Normalize balancing items to list of dicts with carrier_name/share/unit."""
    normalized = []
    for item in items or []:
        if not isinstance(item, dict):
            continue

        carrier_name = clean(item.get("carrier_name"))
        if carrier_name is None:
            carrier_name = clean(item.get("carrier"))

        share = clean(item.get("share"))
        unit = clean(item.get("unit"))

        if carrier_name is None and share is None and unit is None:
            continue

        normalized.append({
            "carrier_name": carrier_name,
            "share": share,
            "unit": unit,
        })

    return normalized


def prune_empty_keys(obj):
    """Recursively remove keys/items that are empty-like."""
    if isinstance(obj, dict):
        cleaned = {}
        for key, value in obj.items():
            pruned = prune_empty_keys(value)
            if not is_empty_like_base(pruned):
                cleaned[key] = pruned
        return cleaned

    if isinstance(obj, list):
        cleaned_list = []
        for value in obj:
            pruned = prune_empty_keys(value)
            if not is_empty_like_base(pruned):
                cleaned_list.append(pruned)
        return cleaned_list

    return obj


def normalize_unit(unit_text):
    if is_nan(unit_text):
        return None
    unit = str(unit_text).strip()
    if not unit or unit == "-":
        return None
    return unit


def split_or_units(unit_text):
    """Split expressions like 'kW or kg/h' into candidate units."""
    if not isinstance(unit_text, str):
        return []
    return [u.strip() for u in re.split(r"\s+or\s+", unit_text, flags=re.IGNORECASE) if u.strip()]


def infer_main_output_unit(main_output_carrier, output_carriers, output_units):
    """Infer the unit for the selected main output carrier."""
    if main_output_carrier is not None:
        for carrier, unit in zip(output_carriers, output_units):
            if clean(carrier) == main_output_carrier:
                unit_norm = normalize_unit(unit)
                if unit_norm:
                    return unit_norm

    # Fallback: first non-empty output unit if main output is not matched.
    for unit in output_units:
        unit_norm = normalize_unit(unit)
        if unit_norm:
            return unit_norm

    return None


def choose_preferred_or_unit(unit_text, main_output_unit):
    """Pick one unit from a disjunctive unit string using output-unit context."""
    candidates = split_or_units(unit_text)
    if not candidates:
        return normalize_unit(unit_text)

    if not main_output_unit:
        return candidates[0]

    target = str(main_output_unit).strip().lower()
    candidates_lower = [c.lower() for c in candidates]

    # Exact match first.
    for idx, cand_lower in enumerate(candidates_lower):
        if cand_lower == target:
            return candidates[idx]

    # Heuristics for common power vs mass-flow disambiguation.
    if ("kg/" in target) or target.startswith("kg") or ("ton/" in target) or target.startswith("t/"):
        for idx, cand_lower in enumerate(candidates_lower):
            if "kg/" in cand_lower or cand_lower.startswith("kg") or "ton/" in cand_lower or cand_lower.startswith("t/"):
                return candidates[idx]

    if ("w" in target) or ("wh" in target) or ("j/s" in target):
        for idx, cand_lower in enumerate(candidates_lower):
            if ("w" in cand_lower) or ("wh" in cand_lower) or ("j/s" in cand_lower):
                return candidates[idx]

    return candidates[0]


def resolve_attribute_unit(attribute_name, unit_text, main_output_unit):
    """Resolve attribute unit; supports context-based choice for 'A or B' units."""
    unit_norm = normalize_unit(unit_text)
    if not unit_norm:
        return None

    # Keep this generic so future attributes with disjunctive units also work.
    if isinstance(unit_norm, str) and re.search(r"\s+or\s+", unit_norm, flags=re.IGNORECASE):
        return choose_preferred_or_unit(unit_norm, main_output_unit)

    return unit_norm


def log_main_output_unit_resolution(tech_name, main_output_carrier, main_output_unit, specs):
    """Print a trace line showing inferred main-output unit and resolved capacity default."""
    capacity_unit_options = None
    for spec in specs:
        if spec.get("attribute_name") == "capacity_min":
            raw_unit = spec.get("unit")
            if isinstance(raw_unit, str) and re.search(r"\s+or\s+", raw_unit, flags=re.IGNORECASE):
                capacity_unit_options = raw_unit
                break

    if capacity_unit_options:
        selected_capacity_unit = choose_preferred_or_unit(capacity_unit_options, main_output_unit)
    else:
        selected_capacity_unit = None

    # print(
    #     f"[unit-resolution] tech '{tech_name}' has main_output '{main_output_carrier}' "
    #     f"with unit '{main_output_unit}', and default capacity unit '{selected_capacity_unit}' is used."
    # )


def build_attribute_specs(mapping_df):
    # new schema does not require description and unit in attribute mapping
    required_cols = {"Raw Attribute", "Cleaned attribute_name", "Assigned Target attribute_id"}
    if not isinstance(mapping_df, pd.DataFrame) or not required_cols.issubset(mapping_df.columns):
        return []

    # canonical attribute_description + unit come from the attribute
    # controlled vocabulary (ds_attr), keyed by attribute_id.
    vocab = {}
    try:
        vocab = {
            str(r["attribute_id"]): (
                clean(r.get("attribute_description")),
                normalize_unit(r.get("unit")),
            )
            for _, r in ds_attr.iterrows()
        }
    except NameError:
        pass

    specs = []
    for _, rec in mapping_df.iterrows():
        raw_attr = clean(rec.get("Raw Attribute"))
        attr_name = clean(rec.get("Cleaned attribute_name"))
        target_attr_id = clean(rec.get("Assigned Target attribute_id"))

        if not raw_attr or not target_attr_id:
            continue

        vocab_desc, vocab_unit = vocab.get(str(target_attr_id), (None, None))

        specs.append({
            "raw_attribute": str(raw_attr),
            # emit the human-readable cleaned name (unmapped stage), not the id
            "attribute_name": str(attr_name) if attr_name else str(target_attr_id),
            "attribute_description": vocab_desc,
            "unit": vocab_unit,
        })

    # De-duplicate by attribute name, keep first mapping row.
    deduped = {}
    for spec in specs:
        deduped.setdefault(spec["attribute_name"], spec)

    return list(deduped.values())


def get_mapped_raw_value(row, raw_attribute, input_carriers, output_carriers):
    # This row in mapping is conceptual; derive from parsed carriers.
    if raw_attribute == "Input, Output for Overall Efficiency":
        combined = input_carriers + output_carriers
        return combined if combined else None

    return clean(row.get(raw_attribute))


def map_technology(row):

    currency = row['Currency']    #!
    cap_unit = infer_main_output_unit(    #!
        clean(row.get("main_output")),      #!
        split_csv(row.get("carriers_out")),     #!
        split_csv(row.get("units_out_ratios")),     #!
    )

    result = {
        "technology_name": (
            row.get("tech_id", "")  #!
            .replace("_", " ")
        ),        

        "technology": {
    "technology_description": clean(row.get("description")),    #!
            "technology_type": clean(row.get("tech_type")),     #!
            "technology_category": clean(row.get("technology_class")),  #!
            "technology_assumption": None,
            "process_name": clean(row.get("unit_operation")),   #!
            "process_type": None,   #!
            "process_category": clean(row.get("tech_category")),    #!
            "process_assumption": None, #!
        },

        "scope": {
            "geographic_scope_description":
                clean(row.get("cost_base")),    #!
            "temporal_scope_description":   #!
                str(row.get("tech_year"))
                if not is_nan(row.get("tech_year"))
                else None,
            "capacity_scope_description":
                clean(row.get("min_installation_size")),
            "system_boundary_description":
                clean(row.get("tech_boundary")),
            "scope_assumption":
                clean(row.get("tech_maturity"))
        },

        "sources": [],
        "attributes": [],
        "balancing": {
            "inputs": [],
            "main_input": clean(row.get("main_input")),     #!
            "outputs": [],
            "main_output": clean(row.get("main_output")),      #!
            "balance_assumption": None,
        },
        "tags": {
            "related_project": "reFuel.ch",
            "tags": []
        }
    }

    attributes = result["attributes"]


    # -----------------------
    # Inputs and outputs for balancing
    # -----------------------
    input_carriers = split_csv(row.get("carriers_in"))  #!
    input_shares = split_csv_float(row.get("ratios_in"))    #!
    input_units = split_csv(row.get("units_in_ratios"))     #!

    output_carriers = split_csv(row.get("carriers_out"))    #!
    output_shares = split_csv_float(row.get("ratios_out"))  #!
    output_units = split_csv(row.get("units_out_ratios"))   #!

    result["balancing"]["inputs"] = to_balance_list(
        build_balancing_entries(
            input_carriers,
            input_shares,
            input_units,
        )
    )
    result["balancing"]["outputs"] = to_balance_list(
        build_balancing_entries(
            output_carriers,
            output_shares,
            output_units,
        )
    )

    main_output_carrier = clean(row.get("main_output")) #!
    main_output_unit = infer_main_output_unit(
        main_output_carrier,
        output_carriers,
        output_units,
    )

    # -----------------------
    # Attributes from mapping CSV only
    # -----------------------
    specs = build_attribute_specs(df_attr_mapping)
    log_main_output_unit_resolution(
        result.get("technology_name"),
        main_output_carrier,
        main_output_unit,
        specs,
    )
    for spec in specs:
        value = get_mapped_raw_value(
            row,
            spec["raw_attribute"],
            input_carriers,
            output_carriers,
        )

        resolved_unit = resolve_attribute_unit(
            spec["attribute_name"],
            spec["unit"],
            main_output_unit,
        )

        add_value(
            attributes,
            spec["attribute_name"],
            spec["attribute_description"],
            value,
            unit=resolved_unit,
        )

    # -----------------------
    # Tags
    # -----------------------
    tags = result["tags"]["tags"]

    for field in [
        "main_sector",
        "main_category",
        "category_spec",
        "tech_type",
        "tech_maturity"
    ]:
        value = clean(row.get(field))
        if value:
            tags.append(str(value))

    return prune_empty_keys(result)

In [17]:
# LAYER 2 (OVERRIDE): compatibility helpers for updated reFuel structure.
# This cell wraps map_technology from Layer 1 and adapts renamed columns.

def _row_get(row, *keys):
    for key in keys:
        if key in row and not is_nan(row.get(key)):
            return row.get(key)
    return None


def _normalize_row_aliases(row):
    """Add legacy aliases expected by Layer 1 mapper when source columns were renamed."""
    row2 = row.copy()

    alias_map = {
        "Currency": "currency",
        "Cost Base": "cost_base",
        "cost_base_year": "tech_year",
        "main_out": "main_output",
        "units_in": "units_in_ratios",
        "units_out": "units_out_ratios",
        "main_category": "tech_category",
        "category_spec": "technology_class",
        "overall_efficiency": "technical_efficiency",
        "capex_one_time_eur": "capex_one_time",
        "capex_power_capacity_eur_per_kw": "capex_per_capacity",
        "opex_one_time_eur": "opex_one_time",
        "opex_fix_power_capacity_eur_per_kw_yr": "opex_per_capacity_yr",
        "opex_energy_eur_per_unit": "opex_per_energy",
        "Min Installation Size": "min_installation_size",
        "Nominal Capacity": "nominal_capacity",
    }

    for legacy_key, new_key in alias_map.items():
        if legacy_key not in row2 or is_nan(row2.get(legacy_key)):
            if new_key in row2 and not is_nan(row2.get(new_key)):
                row2[legacy_key] = row2.get(new_key)

    return row2


def get_mapped_raw_value(row, raw_attribute, input_carriers, output_carriers):
    """Override with aliases for updated ConvTech raw attribute names."""
    if raw_attribute == "Input, Output for Overall Efficiency":
        combined = input_carriers + output_carriers
        return combined if combined else None

    alias_map = {
        "overall_efficiency": "technical_efficiency",
        "capex_one_time_eur": "capex_one_time",
        "capex_power_capacity_eur_per_kw": "capex_per_capacity",
        "opex_one_time_eur": "opex_one_time",
        "opex_fix_power_capacity_eur_per_kw_yr": "opex_per_capacity_yr",
        "opex_energy_eur_per_unit": "opex_per_energy",
    }

    value = clean(_row_get(row, raw_attribute, alias_map.get(raw_attribute, "")))
    return value


def apply_currency_to_units(record, row):
    """Replace CUR placeholder in attribute units with row-level currency."""
    currency = clean(_row_get(row, "Currency", "currency"))
    if not isinstance(currency, str):
        return record

    currency = currency.strip()
    if not currency:
        return record

    attr_list = record.get("attributes")
    if not isinstance(attr_list, list):
        attr_list = record.get("values", [])

    for item in attr_list:
        unit = item.get("unit")
        if isinstance(unit, str) and "CUR" in unit:
            item["unit"] = unit.replace("CUR", currency)

    return record


# Keep wrapper idempotent across re-runs by retaining a stable base function.
_current_map_technology = map_technology
if getattr(_current_map_technology, "_is_wrapper", False):
    _base_map_technology = _current_map_technology._base_map_technology
else:
    _base_map_technology = _current_map_technology

In [18]:
def get_src_attrs(source_text):
    if not source_text or not source_text.strip():
        return []

    # Collect: source_id -> set of linked attributes
    source_to_attrs: dict[str, set] = defaultdict(set)

    # Split on ";" to get individual attribute-group : source(s) segments
    segments = re.split(r";", source_text)

    for segment in segments:
        segment = segment.strip().rstrip(";").strip()
        if not segment:
            continue

        # Split on ":" — left side = quoted attribute names, right side = source IDs
        parts = segment.split(":", 1)
        if len(parts) != 2:
            continue

        attrs_part, sources_part = parts[0].strip(), parts[1].strip()

        # Extract attribute names (quoted strings)
        attributes = re.findall(r'"([^"]+)"', attrs_part)
        attributes = [a.strip() for a in attributes if a.strip()]

        # Extract source IDs (comma-separated, unquoted identifiers)
        # Remove any trailing punctuation or whitespace
        raw_sources = [s.strip().strip('"').strip() for s in sources_part.split(",")]
        source_ids = [s for s in raw_sources if s and s.lower() != "missing"]

        for source_id in source_ids:
            source_to_attrs[source_id].update(attributes)
    
    return source_to_attrs

In [19]:
def parse_source_text(source_text: str) -> list[dict]:
    """
    Parse a raw source_text string of the form:
        "attr1", "attr2": source_id_A; "attr3": source_id_B, source_id_C;
    
    Returns a list of source dicts following the unmapped_record schema:
        [
            {
                "source_description": "source_id_A",
                "source_type": "other",
                "link": "",
                "linked_attribute": ["attr1", "attr2"]
            },
            ...
        ]
    
    Notes:
    - A single attribute can be linked to multiple source IDs (comma-separated after the colon).
    - Duplicate source IDs across segments are merged: their linked_attributes are unioned.
    - Source IDs equal to "missing" are skipped.
    """
    
    source_to_attrs = get_src_attrs(source_text)

    # Build the sources array
    sources = []
    for source_id, linked_attrs in source_to_attrs.items():
        src_name = map_src_id.get(source_id, '')

        ## get source data from `ds_src`
        df = ds_src[ds_src['source_name']==src_name]
        if len(df) == 0:
            print(f'Cannot find source_id "{source_id}" in source dataset')
        elif len(df) > 1:
            print(f'Multiple entries found for source_id "{source_id}" in source dataset; using the first match.')
        else:
            di_src = df.iloc[0].to_dict()

            # new schema does not include source_type and link
            sources.append({
                "source_name": di_src['source_name'],
                "source_description": di_src['description'],
                "linked_attribute": sorted(linked_attrs),
            })

    return sources


def add_sources_to_record(record: dict, source_text: str) -> dict:
    """
    Parse source_text and inject a 'sources' key into the record.

    Args:
        record:      The unmapped_record dict (modified in-place and returned).
        source_text: Raw string from row.get("list_of_source_id").

    Returns:
        The same record dict with 'sources' populated.
    """
    if source_text == source_text:      # skip if source_text is NaN
        record["sources"] = parse_source_text(source_text)
    return record

In [20]:
def map_technology(row):
    """Wrapper: normalize row aliases, build record, and apply unit post-processing."""
    row_norm = _normalize_row_aliases(row)
    rec = _base_map_technology(row_norm)
    rec = apply_currency_to_units(rec, row_norm)

    ## add source 
    source_text = row.get("list_of_source_id", "")
    rec = add_sources_to_record(rec, source_text)

    return rec


map_technology._is_wrapper = True
map_technology._base_map_technology = _base_map_technology

In [21]:
def prepare_convtech_df(df_raw):
    """Normalize ConvTech table where row 1 contains machine-friendly headers."""
    df = df_raw.copy()
    header_idx = 1
    df.columns = [str(c).strip() for c in df.loc[header_idx]]
    df = df.loc[header_idx + 1:].reset_index(drop=True)

    # Remove section/header-like rows
    if "tech_id" in df.columns:
        df = df[df["tech_id"].notna()]
        df = df[df["tech_id"].astype(str).str.strip().str.lower() != "nan"]
        df = df[df["tech_id"].astype(str).str.strip().str.lower() != "tech_id"]
    if "unit_operation" in df.columns:
        df = df[df["unit_operation"].notna()]

    return df.reset_index(drop=True)

### check the content of records

In [22]:
## run record creating for a testing row

# load the data from ConvTech sheet for testing
df_conv = prepare_convtech_df(refuel_data["ConvTech"])

row = df_conv.loc[0]

# run record mapping for the testing row
record = map_technology(row)

In [23]:
# quick check: new balancing payload
record.get("balancing")

{'inputs': [{'carrier_name': 'NH3', 'share': 1.0, 'unit': 'kWh'}],
 'main_input': 'NH3',
 'outputs': [{'carrier_name': 'El13', 'share': 0.58, 'unit': 'kWh'}],
 'main_output': 'El13'}

In [24]:
# quick check: attributes come only from mapping CSV
mapped_attr_names = set(df_attr_mapping["Cleaned attribute_name"].dropna().astype(str).str.strip())
record_attr_entries = record.get("attributes", record.get("values", []))
record_attr_names = {v["attribute_name"] for v in record_attr_entries if isinstance(v, dict) and "attribute_name" in v}

print("record attributes:", len(record_attr_names))
print("not in mapping:", sorted(record_attr_names - mapped_attr_names))

record attributes: 11
not in mapping: []

In [25]:
# quick check: no CUR placeholder should remain after currency replacement
record_attr_entries = record.get("attributes", record.get("values", []))
cur_units = [
    v.get("unit")
    for v in record_attr_entries
    if isinstance(v, dict) and isinstance(v.get("unit"), str) and "CUR" in v.get("unit")
]

print("remaining CUR units:", cur_units)
print("row currency:", row.get("currency", row.get("Currency")))

remaining CUR units: []
row currency: EUR

In [26]:
record.get("attributes", record.get("values", []))

[{'attribute_name': 'technical_efficiency',
  'attribute_description': 'Overall energy conversion efficiency: main output energy / main input energy.',
  'value': '0.58'},
 {'attribute_name': 'technology_readiness_level',
  'attribute_description': 'Technology Readiness Level on the standard 1–9 scale. For non-mature technologies; TRL values progress across tech_year.',
  'value': 9},
 {'attribute_name': 'tech_maturity',
  'attribute_description': 'Aggregated maturity classification derived from TRL. Updated per tech_year.',
  'value': 'Mature'},
 {'attribute_name': 'operating_temperature',
  'attribute_description': 'Typical operating temperature of the process.',
  'unit': '°C',
  'value': 0},
 {'attribute_name': 'power_capacity_min',
  'attribute_description': 'Smallest assumed unit capacity for the technology.',
  'unit': 'CAP',
  'value': 0},
 {'attribute_name': 'lifetime_economic',
  'attribute_description': 'Economic lifetime of the asset.',
  'unit': 'yr',
  'value': 35},
 {'attribute_name': 'capex_one_time',
  'attribute_description': 'Fixed capital expenditure (independent of size).',
  'unit': 'EUR',
  'value': 0},
 {'attribute_name': 'opex_fix_pct_of_capex',
  'attribute_description': 'Fixed annual operational expenditure expressed as a percentage of total CAPEX.',
  'unit': '%',
  'value': 2.92},
 {'attribute_name': 'opex_per_capacity_yr',
  'attribute_description': 'Fixed annual operational expenditure per unit of installed capacity; excluding fuel costs.',
  'unit': 'EUR / CAP.yr',
  'value': 35},
 {'attribute_name': 'opex_per_energy',
  'attribute_description': 'Variable operational expenditure per unit of energy or mass output; excluding fuel costs.',
  'unit': 'EUR / CAP.hr',
  'value': 0.002},
 {'attribute_name': 'opex_one_time',
  'attribute_description': 'Fixed one-time operational expenditure independent of capacity.',
  'unit': 'EUR',
  'value': 0}]

In [27]:
## check of sources
print(f'tech name: {record.get("technology_name")}')
record.get("sources", [])

tech name: NH3 CCGT El

[{'source_name': 'Power-to-Ammonia Renewable Systems Report',
  'source_description': 'Power-to-ammonia in future North European 100 % renewable power and heat system',
  'linked_attribute': ['capex_per_capacity',
   'lifetime_yr',
   'opex_per_capacity_yr',
   'opex_per_energy',
   'technical_efficiency']},
 {'source_name': 'Reaction Input-Output Stoichiometric Conversion',
  'source_description': 'Calculating Input Output Ratios of Reactions',
  'linked_attribute': ['ratios_in', 'ratios_out']},
 {'source_name': 'Danish Energy Agency Technology Dataset 2025',
  'source_description': 'Report from Danish Energy Agency',
  'linked_attribute': ['operating_temperature_c']}]

In [28]:
row['list_of_source_id']

'"capex_per_capacity", "opex_per_capacity_yr", "technical_efficiency", "opex_per_energy", "lifetime_yr": report_power_to_ammonia_2018; "ratios_in", "ratios_out": conversion_parametrization; "operating_temperature_c": report_danish_energy_2025; "ratios_in", "ratios_out": conversion_parametrization;  '

## 3.2 Validate the format of record
check if the content in record match the schema, if there is missing setion or not...

in each the record

In [29]:
# Validate whether one record matches key schema expectations.
# This is written to support future user-provided records too.

def _is_missing(value):
    if value is None:
        return True
    if isinstance(value, str) and value.strip() == "":
        return True
    return False


def _collect_required_unit_attributes(attr_mapping_df):
    """Return attribute names whose unit is defined in mapping and should be present in record."""
    if not isinstance(attr_mapping_df, pd.DataFrame):
        return set()

    required = set()
    required_cols = {"attribute_name", "unit"}
    if not required_cols.issubset(attr_mapping_df.columns):
        return required

    for _, rec in attr_mapping_df.iterrows():
        name = rec.get("attribute_name")
        unit = rec.get("unit")
        if _is_missing(name) or _is_missing(unit):
            continue
        unit_text = str(unit).strip()
        if unit_text != "-":
            required.add(str(name).strip())
    return required


def validate_record_against_schema(record_obj, schema_obj=None, attr_mapping_df=None):
    """Validate record with practical rules derived from current schema and mapping.

    Rules checked:
    1) Required top-level sections exist.
    2) Required nested info exists (technology/scope/balancing minimum keys).
    3) attributes items have required keys (attribute_name, value).
    4) Unit is present when attribute unit is required by mapping.
    5) balancing items have carrier_name and share.
    """
    errors = []
    warnings = []

    if not isinstance(record_obj, dict):
        return {
            "valid": False,
            "errors": ["record must be a dictionary"],
            "warnings": [],
        }

    # Rule 1: required top-level keys
    required_top = [
        "technology_name",
        "technology",
        "scope",
        "attributes",
        "balancing",
    ]
    for key in required_top:
        if key not in record_obj:
            errors.append(f"missing top-level key: {key}")

    # Rule 2: required nested keys
    tech_obj = record_obj.get("technology", {})
    if isinstance(tech_obj, dict):
        for key in ["technology_type", "process_name"]:
            if _is_missing(tech_obj.get(key)):
                errors.append(f"missing technology.{key}")
    else:
        errors.append("technology must be a dictionary")

    scope_obj = record_obj.get("scope", {})
    if isinstance(scope_obj, dict):
        if _is_missing(scope_obj.get("geographic_scope_description")):
            warnings.append("scope.geographic_scope_description is empty")
    else:
        errors.append("scope must be a dictionary")

    bal_obj = record_obj.get("balancing", {})
    if isinstance(bal_obj, dict):
        if "inputs" not in bal_obj and "outputs" not in bal_obj:
            errors.append("balancing must have inputs and/or outputs")
        for side in ["inputs", "outputs"]:
            side_items = bal_obj.get(side, [])
            if side_items is None:
                side_items = []
            if not isinstance(side_items, list):
                errors.append(f"balancing.{side} must be a list")
                continue
            for i, item in enumerate(side_items):
                if not isinstance(item, dict):
                    errors.append(f"balancing.{side}[{i}] must be a dict")
                    continue
                if _is_missing(item.get("carrier_name")):
                    errors.append(f"balancing.{side}[{i}].carrier_name is missing")
                if _is_missing(item.get("share")):
                    errors.append(f"balancing.{side}[{i}].share is missing")
    else:
        errors.append("balancing must be a dictionary")

    # Rule 3 + 4: values structure + required unit when mapping says so
    required_unit_attrs = _collect_required_unit_attributes(attr_mapping_df)
    values_obj = record_obj.get("attributes", [])
    if not isinstance(values_obj, list):
        errors.append("attributes must be a list")
    else:
        seen_attr_names = set()
        for i, item in enumerate(values_obj):
            if not isinstance(item, dict):
                errors.append(f"attributes[{i}] must be a dict")
                continue

            attr_name = item.get("attribute_name")
            attr_value = item.get("value")
            attr_unit = item.get("unit")

            if _is_missing(attr_name):
                errors.append(f"attributes[{i}].attribute_name is missing")
                continue

            attr_name = str(attr_name).strip()
            seen_attr_names.add(attr_name)

            if attr_value is None:
                errors.append(f"attributes[{i}].value is missing for {attr_name}")

            if attr_name in required_unit_attrs and _is_missing(attr_unit):
                errors.append(f"attributes[{i}].unit is required for {attr_name}")

        if len(seen_attr_names) == 0:
            warnings.append("attribute list is empty")

    # Optional Rule 5: alignment with schema keys if schema is available
    if isinstance(schema_obj, dict):
        if "unmapped_entity" not in schema_obj:
            warnings.append("schema does not contain unmapped_entity section")

    return {
        "valid": len(errors) == 0,
        "errors": errors,
        "warnings": warnings,
    }

In [30]:
## load the data from ConvTech sheet for testing
df_conv = prepare_convtech_df(refuel_data["ConvTech"])

row = df_conv.loc[15]

## run record mapping for the testing row
record = map_technology(row)

## run record validation
validation_result = validate_record_against_schema(
    record_obj=record,
    schema_obj=schema_motel,
    attr_mapping_df=df_attr_mapping,
)

## show validation results
print("is_valid:", validation_result["valid"] )
print("error_count:", len(validation_result["errors"]))
print("warning_count:", len(validation_result["warnings"]))

if validation_result["errors"]:
    print("\nErrors:")
    for msg in validation_result["errors"][:20]:
        print("-", msg)

if validation_result["warnings"]:
    print("\nWarnings:")
    for msg in validation_result["warnings"][:20]:
        print("-", msg)

is_valid: True
error_count: 0
warning_count: 0

## 3.3 Convert all data to unmapped_records

In [31]:
## load the data from ConvTech sheet for testing

records = []

df_conv = prepare_convtech_df(refuel_data["ConvTech"])

for indx in df_conv.index[:]:
    row = df_conv.loc[indx]

    ## run record mapping for the testing row
    record = map_technology(row)

    validation_result = validate_record_against_schema(
        record_obj=record,
        schema_obj=schema_motel,
        attr_mapping_df=df_attr_mapping,
    )

    # save validation results
    record['validation_check'] = str(validation_result["valid"])
    if validation_result["valid"]:
        record['validation_note'] = f'erros: {len(validation_result["errors"])}; warnings: {len(validation_result["warnings"])}'

    records.append(record)

    ## show validation results
    print(f'technology_name: {record.get("technology_name")}, indx={indx}')

    if validation_result["errors"]:
        print("\nErrors:")
        for msg in validation_result["errors"][:20]:
            print("-", msg)

    if validation_result["warnings"]:
        print("\nWarnings:")
        for msg in validation_result["warnings"][:20]:
            print("-", msg)

technology_name: NH3 CCGT El, indx=0
technology_name: NH3 OCGT El, indx=1
technology_name: CH4 CCGT El, indx=2
technology_name: CH4 CHP ElTh, indx=3
technology_name: CH4 FuelCell El, indx=4
technology_name: CH4 FuelCell ElBdg, indx=5
technology_name: CH4 OCGT El, indx=6
technology_name: Geothermal CHP ElTh, indx=7
technology_name: H2 CCGT El, indx=8
technology_name: H2 FuelCell El, indx=9
technology_name: H2 FuelCell El, indx=10
technology_name: H2 FuelCell ElBdg, indx=11
technology_name: H2 FuelCell ElBdg, indx=12
technology_name: H2 OCGT El, indx=13
technology_name: El PumpedHydro Pump, indx=14
technology_name: Hydro PumpedTurbine El, indx=15
technology_name: Hydro RunOfRiver El, indx=16
technology_name: Hydro Reservoir El, indx=17
technology_name: MSW Incineration El, indx=18
technology_name: Solar PVAlpine El, indx=19
technology_name: Solar PVAlpine El, indx=20
technology_name: Solar PVAlpine El, indx=21
technology_name: Solar PVAlpine El, indx=22
technology_name: Solar PVRooftop El, indx=23
technology_name: Solar PVRooftop El, indx=24
technology_name: Solar PVRooftop El, indx=25
technology_name: Solar PVRooftop El, indx=26
technology_name: U235 Nuclear El, indx=27
technology_name: Wind Turbine El, indx=28
technology_name: Wind Turbine El, indx=29
technology_name: Wind Turbine El, indx=30
technology_name: Wind Turbine El, indx=31
technology_name: Wood CHP ElTh, indx=32
technology_name: CH4 Boiler ThBdg, indx=33
technology_name: CH4 Boiler ThInd, indx=34
technology_name: El Heater ThBdg, indx=35
technology_name: El Heater ThInd, indx=36
technology_name: El AirCon ThSc, indx=37
Cannot find source_id "linear_interpolation_2020_2050" in source dataset
technology_name: El AirCon ThSc, indx=38
Cannot find source_id "linear_interpolation_2020_2050" in source dataset
technology_name: El AirCon ThSc, indx=39
technology_name: El AirCon ThSc, indx=40
technology_name: H2 Boiler ThInd, indx=41
technology_name: El HeatPump ThBdg, indx=42
technology_name: El HeatPump ThInd, indx=43
Cannot find source_id "linear_interpolation_2020_2050" in source dataset
technology_name: Oil Boiler ThBdg, indx=44
technology_name: Oil Boiler ThInd, indx=45
technology_name: Wood Boiler ThBdg, indx=46
technology_name: Wood Boiler ThInd, indx=47
technology_name: H2 HaberBosch NH3, indx=48
technology_name: BioWet Digestion CH4, indx=49
technology_name: BioWet Digestion CH4, indx=50
technology_name: BioWet Digestion CH4, indx=51
technology_name: H2 Sabatier CH4, indx=52
technology_name: H2 Sabatier CH4, indx=53
technology_name: H2 Sabatier CH4, indx=54
technology_name: H2 Sabatier CH4, indx=55
technology_name: CookingOil HEFA C12, indx=56
technology_name: H2 CO2Hydro MeOH, indx=57
technology_name: H2 CO2Hydro MeOH, indx=58
Cannot find source_id "linear_interpolation_2030_2050" in source dataset
technology_name: H2 CO2Hydro MeOH, indx=59
technology_name: H2 CO2Hydro MeOH, indx=60
technology_name: H2 CO2Hydro MeOH, indx=61
technology_name: H2 RWGS CO, indx=62
technology_name: El Electrolysis H2, indx=63
technology_name: El Electrolysis H2, indx=64
technology_name: El Electrolysis H2, indx=65
technology_name: Syngas FT C12, indx=66
technology_name: Syngas FT C12, indx=67
technology_name: Syngas FT C12, indx=68
technology_name: Syngas FT C12, indx=69
technology_name: Syngas FT C8, indx=70
technology_name: Syngas FT C8, indx=71
technology_name: Syngas FT C8, indx=72
technology_name: Syngas FT C8, indx=73
technology_name: Syngas COHydro CH4, indx=74
technology_name: Syngas COHydro CH4, indx=75
technology_name: Syngas COHydro CH4, indx=76
technology_name: Syngas COHydro CH4, indx=77
technology_name: Syngas COHydro MeOH, indx=78
technology_name: Syngas COHydro MeOH, indx=79
technology_name: Syngas COHydro MeOH, indx=80
technology_name: MSW Gasification Syngas, indx=81

Errors:
- balancing.inputs[1].share is missing
- balancing.outputs[1].share is missing
technology_name: MSW Gasification H2, indx=82

Errors:
- balancing.inputs[1].share is missing
- balancing.outputs[1].share is missing
technology_name: Wood Gasification H2, indx=83
technology_name: Wood Gasification Syngas, indx=84
technology_name: MeOH MtJ C12, indx=85

Errors:
- balancing.inputs[0].share is missing
- balancing.inputs[1].share is missing
- balancing.outputs[0].share is missing
- balancing.outputs[1].share is missing
technology_name: MeOH MtJ C12, indx=86

Errors:
- balancing.inputs[0].share is missing
- balancing.inputs[1].share is missing
- balancing.outputs[0].share is missing
- balancing.outputs[1].share is missing
technology_name: El CoElectrolysis Syngas, indx=87

Errors:
- balancing.inputs[0].share is missing
- balancing.inputs[1].share is missing
- balancing.inputs[2].share is missing
- balancing.outputs[0].share is missing
- balancing.outputs[1].share is missing
- balancing.outputs[2].share is missing
technology_name: El CoElectrolysis Syngas, indx=88

Errors:
- balancing.inputs[0].share is missing
- balancing.inputs[1].share is missing
- balancing.inputs[2].share is missing
- balancing.outputs[0].share is missing
- balancing.outputs[1].share is missing
- balancing.outputs[2].share is missing
technology_name: CH4 Pyrolysis H2, indx=89

Errors:
- balancing.inputs[0].share is missing
- balancing.inputs[1].share is missing
- balancing.outputs[0].share is missing
- balancing.outputs[1].share is missing
technology_name: CH4 Pyrolysis H2, indx=90

Errors:
- balancing.inputs[0].share is missing
- balancing.inputs[1].share is missing
- balancing.outputs[0].share is missing
- balancing.outputs[1].share is missing
technology_name: CO2Flue AmineScrub CO2, indx=91
Cannot find source_id "EP2050+Exkurs" in source dataset
technology_name: BioWet Pyrolysis Biochar, indx=92
technology_name: Air DAC CO2, indx=93
technology_name: Air DAC CO2, indx=94
technology_name: CO2Flue PSA CO2, indx=95
technology_name: CO2Flue PSA CO2, indx=96
technology_name: CO2Flue PSA CO2, indx=97
technology_name: Wood Pyrolysis Biochar, indx=98

In [32]:
## export records to a yaml file
from pathlib import Path

path_export = 'motel-db/unmapped_entity/refuel.yaml'
Path(path_export).parent.mkdir(parents=True, exist_ok=True)
with open(path_export, 'w', encoding='utf-8') as f:
    yaml.dump(records, f, sort_keys=False, allow_unicode=True)

In [33]:
## test to load the yaml file

with open(path_export, 'r', encoding='utf-8') as f:
    loaded_records = yaml.safe_load(f)

loaded_records

[{'technology_name': 'NH3 CCGT El',
  'technology': {'technology_type': 'Conversion',
   'technology_category': 'Gas turbine',
   'process_name': 'CCGT'},
  'scope': {'geographic_scope_description': 'ECA',
   'temporal_scope_description': '2050',
   'capacity_scope_description': 0,
   'system_boundary_description': 'Plant ready to operate',
   'scope_assumption': 'Mature'},
  'attributes': [{'attribute_name': 'technical_efficiency',
    'attribute_description': 'Overall energy conversion efficiency: main output energy / main input energy.',
    'value': '0.58'},
   {'attribute_name': 'technology_readiness_level',
    'attribute_description': 'Technology Readiness Level on the standard 1–9 scale. For non-mature technologies; TRL values progress across tech_year.',
    'value': 9},
   {'attribute_name': 'tech_maturity',
    'attribute_description': 'Aggregated maturity classification derived from TRL. Updated per tech_year.',
    'value': 'Mature'},
   {'attribute_name': 'operating_temperature',
    'attribute_description': 'Typical operating temperature of the process.',
    'unit': '°C',
    'value': 0},
   {'attribute_name': 'power_capacity_min',
    'attribute_description': 'Smallest assumed unit capacity for the technology.',
    'unit': 'CAP',
    'value': 0},
   {'attribute_name': 'lifetime_economic',
    'attribute_description': 'Economic lifetime of the asset.',
    'unit': 'yr',
    'value': 35},
   {'attribute_name': 'capex_one_time',
    'attribute_description': 'Fixed capital expenditure (independent of size).',
    'unit': 'EUR',
    'value': 0},
   {'attribute_name': 'opex_fix_pct_of_capex',
    'attribute_description': 'Fixed annual operational expenditure expressed as a percentage of total CAPEX.',
    'unit': '%',
    'value': 2.92},
   {'attribute_name': 'opex_per_capacity_yr',
    'attribute_description': 'Fixed annual operational expenditure per unit of installed capacity; excluding fuel costs.',
    'unit': 'EUR / CAP.yr',
    'value': 35},
   {'attribute_name': 'opex_per_energy',
    'attribute_description': 'Variable operational expenditure per unit of energy or mass output; excluding fuel costs.',
    'unit': 'EUR / CAP.hr',
    'value': 0.002},
   {'attribute_name': 'opex_one_time',
    'attribute_description': 'Fixed one-time operational expenditure independent of capacity.',
    'unit': 'EUR',
    'value': 0}],
  'balancing': {'inputs': [{'carrier_name': 'NH3',
     'share': 1.0,
     'unit': 'kWh'}],
   'main_input': 'NH3',
   'outputs': [{'carrier_name': 'El13', 'share': 0.58, 'unit': 'kWh'}],
   'main_output': 'El13'},
  'tags': {'related_project': 'reFuel.ch',
   'tags': ['Gas turbine', 'Conversion', 'Mature']},
  'sources': [{'source_name': 'Power-to-Ammonia Renewable Systems Report',
    'source_description': 'Power-to-ammonia in future North European 100 % renewable power and heat system',
    'linked_attribute': ['capex_per_capacity',
     'lifetime_yr',
     'opex_per_capacity_yr',
     'opex_per_energy',
     'technical_efficiency']},
   {'source_name': 'Reaction Input-Output Stoichiometric Conversion',
    'source_description': 'Calculating Input Output Ratios of Reactions',
    'linked_attribute': ['ratios_in', 'ratios_out']},
   {'source_name': 'Danish Energy Agency Technology Dataset 2025',
    'source_description': 'Report from Danish Energy Agency',
    'linked_attribute': ['operating_temperature_c']}],
  'validation_check': 'True',
  'validation_note': 'erros: 0; warnings: 0'},
 {'technology_name': 'NH3 OCGT El',
  'technology': {'technology_type': 'Conversion',
   'technology_category': 'Gas turbine',
   'process_name': 'OCGT'},
  'scope': {'geographic_scope_description': 'ECA',
   'temporal_scope_description': '2050',
   'capacity_scope_description': 0,
   'system_boundary_description': 'Plant ready to operate',
   'scope_assumption': 'Mature'},
  'attributes': [{'attribute_name': 'technical_efficiency',
    'attribute_description': 'Overall energy conversion efficiency: main output energy / main input energy.',
    'value': '0.4'},
   {'attribute_name': 'technology_readiness_level',
    'attribute_description': 'Technology Readiness Level on the standard 1–9 scale. For non-mature technologies; TRL values progress across tech_year.',
    'value': 9},
   {'attribute_name': 'tech_maturity',
    'attribute_description': 'Aggregated maturity classification derived from TRL. Updated per tech_year.',
    'value': 'Mature'},
   {'attribute_name': 'operating_temperature',
    'attribute_description': 'Typical operating temperature of the process.',
    'unit': '°C',
    'value': 0},
   {'attribute_name': 'power_capacity_min',
    'attribute_description': 'Smallest assumed unit capacity for the technology.',
    'unit': 'CAP',
    'value': 0},
   {'attribute_name': 'lifetime_economic',
    'attribute_description': 'Economic lifetime of the asset.',
    'unit': 'yr',
    'value': 30},
   {'attribute_name': 'capex_one_time',
    'attribute_description': 'Fixed capital expenditure (independent of size).',
    'unit': 'EUR',
    'value': 0},
   {'attribute_name': 'opex_fix_pct_of_capex',
    'attribute_description': 'Fixed annual operational expenditure expressed as a percentage of total CAPEX.',
    'unit': '%',
    'value': 2.67},
   {'attribute_name': 'opex_per_capacity_yr',
    'attribute_description': 'Fixed annual operational expenditure per unit of installed capacity; excluding fuel costs.',
    'unit': 'EUR / CAP.yr',
    'value': 20},
   {'attribute_name': 'opex_per_energy',
    'attribute_description': 'Variable operational expenditure per unit of energy or mass output; excluding fuel costs.',
    'unit': 'EUR / CAP.hr',
    'value': 0.002},
   {'attribute_name': 'opex_one_time',
    'attribute_description': 'Fixed one-time operational expenditure independent of capacity.',
    'unit': 'EUR',
    'value': 0}],
  'balancing': {'inputs': [{'carrier_name': 'NH3',
     'share': 1.0,
     'unit': 'kWh'}],
   'main_input': 'NH3',
   'outputs': [{'carrier_name': 'El13', 'share': 0.4, 'unit': 'kWh'}],
   'main_output': 'El13'},
  'tags': {'related_project': 'reFuel.ch',
   'tags': ['Gas turbine', 'Conversion', 'Mature']},
  'sources': [{'source_name': 'Power-to-Ammonia Renewable Systems Report',
    'source_description': 'Power-to-ammonia in future North European 100 % renewable power and heat system',
    'linked_attribute': ['capex_per_capacity',
     'lifetime_yr',
     'opex_per_capacity_yr',
     'opex_per_energy',
     'technical_efficiency']},
   {'source_name': 'Reaction Input-Output Stoichiometric Conversion',
    'source_description': 'Calculating Input Output Ratios of Reactions',
    'linked_attribute': ['ratios_in', 'ratios_out']},
   {'source_name': 'Danish Energy Agency Technology Dataset 2025',
    'source_description': 'Report from Danish Energy Agency',
    'linked_attribute': ['operating_temperature_c']}],
  'validation_check': 'True',
  'validation_note': 'erros: 0; warnings: 0'},
 {'technology_name': 'CH4 CCGT El',
  'technology': {'technology_description': 'Methane-fueled CCGT with carbon capture and storage (CCS) (2030).',
   'technology_type': 'Conversion',
   'technology_category': 'Gas turbine',
   'process_name': 'CCGT'},
  'scope': {'geographic_scope_description': 'ECA',
   'temporal_scope_description': '2050',
   'capacity_scope_description': 400000,
   'system_boundary_description': 'Plant ready to operate',
   'scope_assumption': 'Mature'},
  'attributes': [{'attribute_name': 'technical_efficiency',
    'attribute_description': 'Overall energy conversion efficiency: main output energy / main input energy.',
    'value': '0.64'},
   {'attribute_name': 'technology_readiness_level',
    'attribute_description': 'Technology Readiness Level on the standard 1–9 scale. For non-mature technologies; TRL values progress across tech_year.',
    'value': 9},
   {'attribute_name': 'tech_maturity',
    'attribute_description': 'Aggregated maturity classification derived from TRL. Updated per tech_year.',
    'value': 'Mature'},
   {'attribute_name': 'operating_temperature',
    'attribute_description': 'Typical operating temperature of the process.',
    'unit': '°C',
    'value': 1500},
   {'attribute_name': 'power_capacity_min',
    'attribute_description': 'Smallest assumed unit capacity for the technology.',
    'unit': 'CAP',
    'value': 400000},
   {'attribute_name': 'lifetime_economic',
    'attribute_description': 'Economic lifetime of the asset.',
    'unit': 'yr',
    'value': 23},
   {'attribute_name': 'capex_one_time',
    'attribute_description': 'Fixed capital expenditure (independent of size).',
    'unit': 'EUR',
    'value': 0},
   {'attribute_name': 'opex_fix_pct_of_capex',
    'attribute_description': 'Fixed annual operational expenditure expressed as a percentage of total CAPEX.',
    'unit': '%',
    'value': 2.36},
   {'attribute_name': 'opex_per_capacity_yr',
    'attribute_description': 'Fixed annual operational expenditure per unit of installed capacity; excluding fuel costs.',
    'unit': 'EUR / CAP.yr',
    'value': 21},
   {'attribute_name': 'opex_per_energy',
    'attribute_description': 'Variable operational expenditure per unit of energy or mass output; excluding fuel costs.',
    'unit': 'EUR / CAP.hr',
    'value': 0.002},
   {'attribute_name': 'uncertainty_rating',
    'attribute_description': 'Flag indicating whether parameter values have been cross-checked against literature ranges.',
    'value': 'Low'},
   {'attribute_name': 'opex_one_time',
    'attribute_description': 'Fixed one-time operational expenditure independent of capacity.',
    'unit': 'EUR',
    'value': 0}],
  'balancing': {'inputs': [{'carrier_name': 'CH4',
     'share': 1.0,
     'unit': 'kWh'}],
   'main_input': 'CH4',
   'outputs': [{'carrier_name': 'El13', 'share': 0.61, 'unit': 'kWh'}],
   'main_output': 'El13'},
  'tags': {'related_project': 'reFuel.ch',
   'tags': ['Gas turbine', 'Conversion', 'Mature']},
  'sources': [{'source_name': 'Electricity Market Combined Cycle Modelling Study',
    'source_description': 'Modelling combined-cycle power plants in a detailed electricity market',
    'linked_attribute': ['technical_efficiency']},
   {'source_name': 'VSE Energiezukunft 2050 Update',
    'source_description': 'VSE Energiezukunft 2050, Update 2025',
    'linked_attribute': ['capex_per_capacity',
     'opex_per_capacity_yr',
     'opex_per_energy']},
   {'source_name': 'VSE Energiezukunft 2050 Study',
    'source_description': 'VSE Energiezukunft 2050, Studie 2022',
    'linked_attribute': ['lifetime_yr', 'technical_efficiency']}],
  'validation_check': 'True',
  'validation_note': 'erros: 0; warnings: 0'},
 {'technology_name': 'CH4 CHP ElTh',
  'technology': {'technology_description': 'Combined heat and power (CHP) generation using methane (CH₄).',
   'technology_type': 'Conversion',
   'technology_category': 'Combined heat & power',
   'process_name': 'CHP plant'},
  'scope': {'geographic_scope_description': 'ECA',
   'temporal_scope_description': '2050',
   'capacity_scope_description': 1000,
   'system_boundary_description': 'Plant ready to operate',
   'scope_assumption': 'Mature'},
  'attributes': [{'attribute_name': 'technical_efficiency',
    'attribute_description': 'Overall energy conversion efficiency: main output energy / main input energy.',
    'value': '0.3'},
   {'attribute_name': 'technology_readiness_level',
    'attribute_description': 'Technology Readiness Level on the standard 1–9 scale. For non-mature technologies; TRL values progress across tech_year.',
    'value': 9},
   {'attribute_name': 'tech_maturity',
    'attribute_description': 'Aggregated maturity classification derived from TRL. Updated per tech_year.',
    'value': 'Mature'},
   {'attribute_name': 'operating_temperature',
    'attribute_description': 'Typical operating temperature of the process.',
    'unit': '°C',
    'value': 0},
   {'attribute_name': 'power_capacity_min',
    'attribute_description': 'Smallest assumed unit capacity for the technology.',
    'unit': 'CAP',
    'value': 1000},
   {'attribute_name': 'lifetime_economic',
    'attribute_description': 'Economic lifetime of the asset.',
    'unit': 'yr',
    'value': 15},
   {'attribute_name': 'capex_one_time',
    'attribute_description': 'Fixed capital expenditure (independent of size).',
    'unit': 'EUR',
    'value': 0},
   {'attribute_name': 'opex_fix_pct_of_capex',
    'attribute_description': 'Fixed annual operational expenditure expressed as a percentage of total CAPEX.',
    'unit': '%',
    'value': 1.2},
   {'attribute_name': 'opex_per_capacity_yr',
    'attribute_description': 'Fixed annual operational expenditure per unit of installed capacity; excluding fuel costs.',
    'unit': 'EUR / CAP.yr',
    'value': 12},
   {'attribute_name': 'opex_per_energy',
    'attribute_description': 'Variable operational expenditure per unit of energy or mass output; excluding fuel costs.',
    'unit': 'EUR / CAP.hr',
    'value': 0.004},
   {'attribute_name': 'uncertainty_rating',
    'attribute_description': 'Flag indicating whether parameter values have been cross-checked against literature ranges.',
    'value': 'Low'},
   {'attribute_name': 'opex_one_time',
    'attribute_description': 'Fixed one-time operational expenditure independent of capacity.',
    'unit': 'EUR',
    'value': 0}],
  'balancing': {'inputs': [{'carrier_name': 'CH4',
     'share': 1.0,
     'unit': 'kWh'}],
   'main_input': 'CH4',
   'outputs': [{'carrier_name': 'El47', 'share': 0.3, 'unit': 'kWh'},
    {'carrier_name': 'ThHt', 'share': 0.6, 'unit': 'kWh'}],
   'main_output': 'El47'},
  'tags': {'related_project': 'reFuel.ch',
   'tags': ['Combined heat & power', 'Conversion', 'Mature']},
  'sources': [{'source_name': 'VSE Energiezukunft 2050 Update',
    'source_description': 'VSE Energiezukunft 2050, Update 2025',
    'linked_attribute': ['capex_per_capacity',
     'opex_per_capacity_yr',
     'opex_per_energy',
     'technical_efficiency']},
   {'source_name': 'VSE Energiezukunft 2050 Study',
    'source_description': 'VSE Energiezukunft 2050, Studie 2022',
    'linked_attribute': ['lifetime_yr']},
   {'source_name': 'Process Input-Output Share Allocation Reference',
    'source_description': 'Temporary reference ID for input and output shares',
    'linked_attribute': ['ratios_in', 'ratios_out']}],
  'validation_check': 'True',
  'validation_note': 'erros: 0; warnings: 0'},
 {'technology_name': 'CH4 FuelCell El',
  'technology': {'technology_description': 'Methane-fueled fuel cell electricity generation at El47 (2030).',
   'technology_type': 'Conversion',
   'technology_category': 'Fuel cell',
   'process_name': 'SOFC'},
  'scope': {'geographic_scope_description': 'ECA',
   'temporal_scope_description': '2030',
   'capacity_scope_description': 0,
   'system_boundary_description': 'Plant ready to operate',
   'scope_assumption': 'Mature'},
  'attributes': [{'attribute_name': 'technical_efficiency',
    'attribute_description': 'Overall energy conversion efficiency: main output energy / main input energy.',
    'value': '0.64'},
   {'attribute_name': 'technology_readiness_level',
    'attribute_description': 'Technology Readiness Level on the standard 1–9 scale. For non-mature technologies; TRL values progress across tech_year.',
    'value': 9},
   {'attribute_name': 'tech_maturity',
    'attribute_description': 'Aggregated maturity classification derived from TRL. Updated per tech_year.',
    'value': 'Mature'},
   {'attribute_name': 'operating_temperature',
    'attribute_description': 'Typical operating temperature of the process.',
    'unit': '°C',
    'value': 1000},
   {'attribute_name': 'power_capacity_min',
    'attribute_description': 'Smallest assumed unit capacity for the technology.',
    'unit': 'CAP',
    'value': 0},
   {'attribute_name': 'lifetime_economic',
    'attribute_description': 'Economic lifetime of the asset.',
    'unit': 'yr',
    'value': 16},
   {'attribute_name': 'capex_one_time',
    'attribute_description': 'Fixed capital expenditure (independent of size).',
    'unit': 'EUR',
    'value': 0},
   {'attribute_name': 'opex_fix_pct_of_capex',
    'attribute_description': 'Fixed annual operational expenditure expressed as a percentage of total CAPEX.',
    'unit': '%',
    'value': 1.03},
   {'attribute_name': 'opex_per_capacity_yr',
    'attribute_description': 'Fixed annual operational expenditure per unit of installed capacity; excluding fuel costs.',
    'unit': 'EUR / CAP.yr',
    'value': 62},
   {'attribute_name': 'opex_per_energy',
    'attribute_description': 'Variable operational expenditure per unit of energy or mass output; excluding fuel costs.',
    'unit': 'EUR / CAP.hr',
    'value': 0},
   {'attribute_name': 'uncertainty_rating',
    'attribute_description': 'Flag indicating whether parameter values have been cross-checked against literature ranges.',
    'value': 'Medium'},
   {'attribute_name': 'opex_one_time',
    'attribute_description': 'Fixed one-time operational expenditure independent of capacity.',
    'unit': 'EUR',
    'value': 0}],
  'balancing': {'inputs': [{'carrier_name': 'CH4',
     'share': 1.0,
     'unit': 'kWh'}],
   'main_input': 'CH4',
   'outputs': [{'carrier_name': 'El47', 'share': 0.58, 'unit': 'kWh'},
    {'carrier_name': 'ThHt', 'share': 0.28, 'unit': 'kWh'}],
   'main_output': 'El47'},
  'tags': {'related_project': 'reFuel.ch',
   'tags': ['Fuel cell', 'Conversion', 'Mature']},
  'sources': [{'source_name': 'Joint Research Centre Technical Report',
    'source_description': nan,
    'linked_attribute': ['capex_per_capacity',
     'lifetime_yr',
     'opex_per_capacity_yr',
     'technical_efficiency']},
   {'source_name': 'Process Input-Output Share Allocation Reference',
    'source_description': 'Temporary reference ID for input and output shares',
    'linked_attribute': ['ratios_in', 'ratios_out']}],
  'validation_check': 'True',
  'validation_note': 'erros: 0; warnings: 0'},
 {'technology_name': 'CH4 FuelCell ElBdg',
  'technology': {'technology_description': 'Methane-fueled fuel cell electricity generation in buildings (2030).',
   'technology_type': 'Conversion',
   'technology_category': 'Fuel cell',
   'process_name': 'SOFC'},
  'scope': {'geographic_scope_description': 'ECA',
   'temporal_scope_description': '2030',
   'capacity_scope_description': 0,
   'system_boundary_description': 'Plant ready to operate',
   'scope_assumption': 'Mature'},
  'attributes': [{'attribute_name': 'technical_efficiency',
    'attribute_description': 'Overall energy conversion efficiency: main output energy / main input energy.',
    'value': '0.64'},
   {'attribute_name': 'technology_readiness_level',
    'attribute_description': 'Technology Readiness Level on the standard 1–9 scale. For non-mature technologies; TRL values progress across tech_year.',
    'value': 9},
   {'attribute_name': 'tech_maturity',
    'attribute_description': 'Aggregated maturity classification derived from TRL. Updated per tech_year.',
    'value': 'Mature'},
   {'attribute_name': 'operating_temperature',
    'attribute_description': 'Typical operating temperature of the process.',
    'unit': '°C',
    'value': 1000},
   {'attribute_name': 'power_capacity_min',
    'attribute_description': 'Smallest assumed unit capacity for the technology.',
    'unit': 'CAP',
    'value': 0},
   {'attribute_name': 'lifetime_economic',
    'attribute_description': 'Economic lifetime of the asset.',
    'unit': 'yr',
    'value': 16},
   {'attribute_name': 'capex_one_time',
    'attribute_description': 'Fixed capital expenditure (independent of size).',
    'unit': 'EUR',
    'value': 0},
   {'attribute_name': 'opex_fix_pct_of_capex',
    'attribute_description': 'Fixed annual operational expenditure expressed as a percentage of total CAPEX.',
    'unit': '%',
    'value': 2.82},
   {'attribute_name': 'opex_per_capacity_yr',

In [34]:
len(loaded_records)

99

In [35]:
loaded_records[0]

{'technology_name': 'NH3 CCGT El',
 'technology': {'technology_type': 'Conversion',
  'technology_category': 'Gas turbine',
  'process_name': 'CCGT'},
 'scope': {'geographic_scope_description': 'ECA',
  'temporal_scope_description': '2050',
  'capacity_scope_description': 0,
  'system_boundary_description': 'Plant ready to operate',
  'scope_assumption': 'Mature'},
 'attributes': [{'attribute_name': 'technical_efficiency',
   'attribute_description': 'Overall energy conversion efficiency: main output energy / main input energy.',
   'value': '0.58'},
  {'attribute_name': 'technology_readiness_level',
   'attribute_description': 'Technology Readiness Level on the standard 1–9 scale. For non-mature technologies; TRL values progress across tech_year.',
   'value': 9},
  {'attribute_name': 'tech_maturity',
   'attribute_description': 'Aggregated maturity classification derived from TRL. Updated per tech_year.',
   'value': 'Mature'},
  {'attribute_name': 'operating_temperature',
   'attribute_description': 'Typical operating temperature of the process.',
   'unit': '°C',
   'value': 0},
  {'attribute_name': 'power_capacity_min',
   'attribute_description': 'Smallest assumed unit capacity for the technology.',
   'unit': 'CAP',
   'value': 0},
  {'attribute_name': 'lifetime_economic',
   'attribute_description': 'Economic lifetime of the asset.',
   'unit': 'yr',
   'value': 35},
  {'attribute_name': 'capex_one_time',
   'attribute_description': 'Fixed capital expenditure (independent of size).',
   'unit': 'EUR',
   'value': 0},
  {'attribute_name': 'opex_fix_pct_of_capex',
   'attribute_description': 'Fixed annual operational expenditure expressed as a percentage of total CAPEX.',
   'unit': '%',
   'value': 2.92},
  {'attribute_name': 'opex_per_capacity_yr',
   'attribute_description': 'Fixed annual operational expenditure per unit of installed capacity; excluding fuel costs.',
   'unit': 'EUR / CAP.yr',
   'value': 35},
  {'attribute_name': 'opex_per_energy',
   'attribute_description': 'Variable operational expenditure per unit of energy or mass output; excluding fuel costs.',
   'unit': 'EUR / CAP.hr',
   'value': 0.002},
  {'attribute_name': 'opex_one_time',
   'attribute_description': 'Fixed one-time operational expenditure independent of capacity.',
   'unit': 'EUR',
   'value': 0}],
 'balancing': {'inputs': [{'carrier_name': 'NH3',
    'share': 1.0,
    'unit': 'kWh'}],
  'main_input': 'NH3',
  'outputs': [{'carrier_name': 'El13', 'share': 0.58, 'unit': 'kWh'}],
  'main_output': 'El13'},
 'tags': {'related_project': 'reFuel.ch',
  'tags': ['Gas turbine', 'Conversion', 'Mature']},
 'sources': [{'source_name': 'Power-to-Ammonia Renewable Systems Report',
   'source_description': 'Power-to-ammonia in future North European 100 % renewable power and heat system',
   'linked_attribute': ['capex_per_capacity',
    'lifetime_yr',
    'opex_per_capacity_yr',
    'opex_per_energy',
    'technical_efficiency']},
  {'source_name': 'Reaction Input-Output Stoichiometric Conversion',
   'source_description': 'Calculating Input Output Ratios of Reactions',
   'linked_attribute': ['ratios_in', 'ratios_out']},
  {'source_name': 'Danish Energy Agency Technology Dataset 2025',
   'source_description': 'Report from Danish Energy Agency',
   'linked_attribute': ['operating_temperature_c']}],
 'validation_check': 'True',
 'validation_note': 'erros: 0; warnings: 0'}